/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: matrix3x3f.proto */

#ifndef PROTOBUF_C_matrix3x3f_2eproto__INCLUDED
#define PROTOBUF_C_matrix3x3f_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Ltpb__Matrix3x3F Ltpb__Matrix3x3F;


/* --- enums --- */


/* --- messages --- */

/*
 * Structure to hold 3 x 3 matrix (floating point precision)
 */
struct  _Ltpb__Matrix3x3F
{
  ProtobufCMessage base;
  /*
   * / Writing this in a row major format
   */
  /*
   * matrix(0,0)
   */
  float x00;
  /*
   * matrix(0,1)
   */
  float x01;
  /*
   * matrix(0,2)
   */
  float x02;
  /*
   * matrix(1,0)
   */
  float x10;
  /*
   * matrix(1,1)
   */
  float x11;
  /*
   * matrix(1,2)
   */
  float x12;
  /*
   * matrix(2,0)
   */
  float x20;
  /*
   * matrix(2,1)
   */
  float x21;
  /*
   * matrix(2,2)
   */
  float x22;
};
#define LTPB__MATRIX3X3_F__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ltpb__matrix3x3_f__descriptor) \
    , 0, 0, 0, 0, 0, 0, 0, 0, 0 }


/* Ltpb__Matrix3x3F methods */
void   ltpb__matrix3x3_f__init
                     (Ltpb__Matrix3x3F         *message);
size_t ltpb__matrix3x3_f__get_packed_size
                     (const Ltpb__Matrix3x3F   *message);
size_t ltpb__matrix3x3_f__pack
                     (const Ltpb__Matrix3x3F   *message,
                      uint8_t             *out);
size_t ltpb__matrix3x3_f__pack_to_buffer
                     (const Ltpb__Matrix3x3F   *message,
                      ProtobufCBuffer     *buffer);
Ltpb__Matrix3x3F *
       ltpb__matrix3x3_f__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ltpb__matrix3x3_f__free_unpacked
                     (Ltpb__Matrix3x3F *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Ltpb__Matrix3x3F_Closure)
                 (const Ltpb__Matrix3x3F *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor ltpb__matrix3x3_f__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_matrix3x3f_2eproto__INCLUDED */
