/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proximity_sensors.proto */

#ifndef PROTOBUF_C_proximity_5fsensors_2eproto__INCLUDED
#define PROTOBUF_C_proximity_5fsensors_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Ltpb__ProximitySensors Ltpb__ProximitySensors;


/* --- enums --- */


/* --- messages --- */

/*
 * this structure holds device proximity sensors state
 */
struct  _Ltpb__ProximitySensors
{
  ProtobufCMessage base;
  protobuf_c_boolean sensor_1;
  protobuf_c_boolean sensor_2;
  protobuf_c_boolean sensor_3;
  protobuf_c_boolean sensor_4;
  protobuf_c_boolean sensor_5;
};
#define LTPB__PROXIMITY_SENSORS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ltpb__proximity_sensors__descriptor) \
    , 0, 0, 0, 0, 0 }


/* Ltpb__ProximitySensors methods */
void   ltpb__proximity_sensors__init
                     (Ltpb__ProximitySensors         *message);
size_t ltpb__proximity_sensors__get_packed_size
                     (const Ltpb__ProximitySensors   *message);
size_t ltpb__proximity_sensors__pack
                     (const Ltpb__ProximitySensors   *message,
                      uint8_t             *out);
size_t ltpb__proximity_sensors__pack_to_buffer
                     (const Ltpb__ProximitySensors   *message,
                      ProtobufCBuffer     *buffer);
Ltpb__ProximitySensors *
       ltpb__proximity_sensors__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ltpb__proximity_sensors__free_unpacked
                     (Ltpb__ProximitySensors *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Ltpb__ProximitySensors_Closure)
                 (const Ltpb__ProximitySensors *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor ltpb__proximity_sensors__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_proximity_5fsensors_2eproto__INCLUDED */
