/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sensor_type.proto */

#ifndef PROTOBUF_C_sensor_5ftype_2eproto__INCLUDED
#define PROTOBUF_C_sensor_5ftype_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif




/* --- enums --- */

typedef enum _Ltpb__SensorType {
  LTPB__SENSOR_TYPE__SENSOR_UNKNOWN = 0,
  LTPB__SENSOR_TYPE__SENSOR_AR835 = 1,
  LTPB__SENSOR_TYPE__SENSOR_AR1335 = 2,
  LTPB__SENSOR_TYPE__SENSOR_AR1335_MONO = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LTPB__SENSOR_TYPE)
} Ltpb__SensorType;

/* --- messages --- */

/* --- per-message closures --- */


/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    ltpb__sensor_type__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_sensor_5ftype_2eproto__INCLUDED */
