/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: camera_id.proto */

#ifndef PROTOBUF_C_camera_5fid_2eproto__INCLUDED
#define PROTOBUF_C_camera_5fid_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif




/* --- enums --- */

typedef enum _Ltpb__CameraID {
  LTPB__CAMERA_ID__A1 = 0,
  LTPB__CAMERA_ID__A2 = 1,
  LTPB__CAMERA_ID__A3 = 2,
  LTPB__CAMERA_ID__A4 = 3,
  LTPB__CAMERA_ID__A5 = 4,
  LTPB__CAMERA_ID__B1 = 5,
  LTPB__CAMERA_ID__B2 = 6,
  LTPB__CAMERA_ID__B3 = 7,
  LTPB__CAMERA_ID__B4 = 8,
  LTPB__CAMERA_ID__B5 = 9,
  LTPB__CAMERA_ID__C1 = 10,
  LTPB__CAMERA_ID__C2 = 11,
  LTPB__CAMERA_ID__C3 = 12,
  LTPB__CAMERA_ID__C4 = 13,
  LTPB__CAMERA_ID__C5 = 14,
  LTPB__CAMERA_ID__C6 = 15
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LTPB__CAMERA_ID)
} Ltpb__CameraID;

/* --- messages --- */

/* --- per-message closures --- */


/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    ltpb__camera_id__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_camera_5fid_2eproto__INCLUDED */
