/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: device_temp.proto */

#ifndef PROTOBUF_C_device_5ftemp_2eproto__INCLUDED
#define PROTOBUF_C_device_5ftemp_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Ltpb__DeviceTemp Ltpb__DeviceTemp;


/* --- enums --- */


/* --- messages --- */

/*
 * this structure holds device internal temperature measurements excluding imaging sensor
 * which are stored inside camera_module.proto
 * All temperature measurments are expressed in centigrade celsius (C)
 */
struct  _Ltpb__DeviceTemp
{
  ProtobufCMessage base;
  int32_t sensor_1;
  int32_t sensor_2;
  int32_t sensor_3;
  int32_t sensor_4;
  protobuf_c_boolean has_flex_sensor_1;
  int32_t flex_sensor_1;
};
#define LTPB__DEVICE_TEMP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ltpb__device_temp__descriptor) \
    , 0, 0, 0, 0, 0,0 }


/* Ltpb__DeviceTemp methods */
void   ltpb__device_temp__init
                     (Ltpb__DeviceTemp         *message);
size_t ltpb__device_temp__get_packed_size
                     (const Ltpb__DeviceTemp   *message);
size_t ltpb__device_temp__pack
                     (const Ltpb__DeviceTemp   *message,
                      uint8_t             *out);
size_t ltpb__device_temp__pack_to_buffer
                     (const Ltpb__DeviceTemp   *message,
                      ProtobufCBuffer     *buffer);
Ltpb__DeviceTemp *
       ltpb__device_temp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ltpb__device_temp__free_unpacked
                     (Ltpb__DeviceTemp *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Ltpb__DeviceTemp_Closure)
                 (const Ltpb__DeviceTemp *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor ltpb__device_temp__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_device_5ftemp_2eproto__INCLUDED */
