/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: flash_calibration.proto */

#ifndef PROTOBUF_C_flash_5fcalibration_2eproto__INCLUDED
#define PROTOBUF_C_flash_5fcalibration_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Ltpb__FlashCalibration Ltpb__FlashCalibration;


/* --- enums --- */


/* --- messages --- */

struct  _Ltpb__FlashCalibration
{
  ProtobufCMessage base;
  /*
   * measured lux in the box of cool white led
   */
  float ledcool_lux;
  /*
   * maximum lumens of cool white led
   */
  float ledcool_max_lumens;
  /*
   * cct of cool white led in Kelvin
   */
  float ledcool_cct;
  /*
   * measured lux in the box of warm white led
   */
  float ledwarm_lux;
  /*
   * maximum lumens of warm white led
   */
  float ledwarm_max_lumens;
  /*
   * cct of warm white led in Kelvin
   */
  float ledwarm_cct;
};
#define LTPB__FLASH_CALIBRATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ltpb__flash_calibration__descriptor) \
    , 0, 0, 0, 0, 0, 0 }


/* Ltpb__FlashCalibration methods */
void   ltpb__flash_calibration__init
                     (Ltpb__FlashCalibration         *message);
size_t ltpb__flash_calibration__get_packed_size
                     (const Ltpb__FlashCalibration   *message);
size_t ltpb__flash_calibration__pack
                     (const Ltpb__FlashCalibration   *message,
                      uint8_t             *out);
size_t ltpb__flash_calibration__pack_to_buffer
                     (const Ltpb__FlashCalibration   *message,
                      ProtobufCBuffer     *buffer);
Ltpb__FlashCalibration *
       ltpb__flash_calibration__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ltpb__flash_calibration__free_unpacked
                     (Ltpb__FlashCalibration *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Ltpb__FlashCalibration_Closure)
                 (const Ltpb__FlashCalibration *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor ltpb__flash_calibration__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_flash_5fcalibration_2eproto__INCLUDED */
