/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: imu_data.proto */

#ifndef PROTOBUF_C_imu_5fdata_2eproto__INCLUDED
#define PROTOBUF_C_imu_5fdata_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "point3f.pb-c.h"

typedef struct _Ltpb__IMUData Ltpb__IMUData;
typedef struct _Ltpb__IMUData__Sample Ltpb__IMUData__Sample;


/* --- enums --- */


/* --- messages --- */

struct  _Ltpb__IMUData__Sample
{
  ProtobufCMessage base;
  /*
   * sensor row index (where 0 means top-most row) associated with this measurement
   */
  uint32_t row_idx;
  /*
   * measurement data
   */
  Ltpb__Point3F *data;
};
#define LTPB__IMUDATA__SAMPLE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ltpb__imudata__sample__descriptor) \
    , 0, NULL }


struct  _Ltpb__IMUData
{
  ProtobufCMessage base;
  /*
   * accelerometer data stored in Gs
   */
  size_t n_accelerometer;
  Ltpb__IMUData__Sample **accelerometer;
  /*
   * gyro data stored in degrees per second
   */
  size_t n_gyroscope;
  Ltpb__IMUData__Sample **gyroscope;
};
#define LTPB__IMUDATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ltpb__imudata__descriptor) \
    , 0,NULL, 0,NULL }


/* Ltpb__IMUData__Sample methods */
void   ltpb__imudata__sample__init
                     (Ltpb__IMUData__Sample         *message);
/* Ltpb__IMUData methods */
void   ltpb__imudata__init
                     (Ltpb__IMUData         *message);
size_t ltpb__imudata__get_packed_size
                     (const Ltpb__IMUData   *message);
size_t ltpb__imudata__pack
                     (const Ltpb__IMUData   *message,
                      uint8_t             *out);
size_t ltpb__imudata__pack_to_buffer
                     (const Ltpb__IMUData   *message,
                      ProtobufCBuffer     *buffer);
Ltpb__IMUData *
       ltpb__imudata__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ltpb__imudata__free_unpacked
                     (Ltpb__IMUData *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Ltpb__IMUData__Sample_Closure)
                 (const Ltpb__IMUData__Sample *message,
                  void *closure_data);
typedef void (*Ltpb__IMUData_Closure)
                 (const Ltpb__IMUData *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor ltpb__imudata__descriptor;
extern const ProtobufCMessageDescriptor ltpb__imudata__sample__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_imu_5fdata_2eproto__INCLUDED */
