/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: point2i.proto */

#ifndef PROTOBUF_C_point2i_2eproto__INCLUDED
#define PROTOBUF_C_point2i_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Ltpb__Point2I Ltpb__Point2I;


/* --- enums --- */


/* --- messages --- */

struct  _Ltpb__Point2I
{
  ProtobufCMessage base;
  int32_t x;
  int32_t y;
};
#define LTPB__POINT2_I__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ltpb__point2_i__descriptor) \
    , 0, 0 }


/* Ltpb__Point2I methods */
void   ltpb__point2_i__init
                     (Ltpb__Point2I         *message);
size_t ltpb__point2_i__get_packed_size
                     (const Ltpb__Point2I   *message);
size_t ltpb__point2_i__pack
                     (const Ltpb__Point2I   *message,
                      uint8_t             *out);
size_t ltpb__point2_i__pack_to_buffer
                     (const Ltpb__Point2I   *message,
                      ProtobufCBuffer     *buffer);
Ltpb__Point2I *
       ltpb__point2_i__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ltpb__point2_i__free_unpacked
                     (Ltpb__Point2I *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Ltpb__Point2I_Closure)
                 (const Ltpb__Point2I *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor ltpb__point2_i__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_point2i_2eproto__INCLUDED */
