/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: range2f.proto */

#ifndef PROTOBUF_C_range2f_2eproto__INCLUDED
#define PROTOBUF_C_range2f_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Ltpb__Range2F Ltpb__Range2F;


/* --- enums --- */


/* --- messages --- */

/*
 * Represents a range of values that a variable can take. 
 */
struct  _Ltpb__Range2F
{
  ProtobufCMessage base;
  /*
   * Minimum value 
   */
  float min_val;
  /*
   * Maximum value 
   */
  float max_val;
};
#define LTPB__RANGE2_F__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ltpb__range2_f__descriptor) \
    , 0, 0 }


/* Ltpb__Range2F methods */
void   ltpb__range2_f__init
                     (Ltpb__Range2F         *message);
size_t ltpb__range2_f__get_packed_size
                     (const Ltpb__Range2F   *message);
size_t ltpb__range2_f__pack
                     (const Ltpb__Range2F   *message,
                      uint8_t             *out);
size_t ltpb__range2_f__pack_to_buffer
                     (const Ltpb__Range2F   *message,
                      ProtobufCBuffer     *buffer);
Ltpb__Range2F *
       ltpb__range2_f__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ltpb__range2_f__free_unpacked
                     (Ltpb__Range2F *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Ltpb__Range2F_Closure)
                 (const Ltpb__Range2F *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor ltpb__range2_f__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_range2f_2eproto__INCLUDED */
