/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: time_stamp.proto */

#ifndef PROTOBUF_C_time_5fstamp_2eproto__INCLUDED
#define PROTOBUF_C_time_5fstamp_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Ltpb__TimeStamp Ltpb__TimeStamp;


/* --- enums --- */


/* --- messages --- */

struct  _Ltpb__TimeStamp
{
  ProtobufCMessage base;
  uint32_t year;
  /*
   * should this be a string of month name?
   */
  uint32_t month;
  uint32_t day;
  /*
   * in 24 hour format
   */
  uint32_t hour;
  uint32_t minute;
  uint32_t second;
};
#define LTPB__TIME_STAMP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ltpb__time_stamp__descriptor) \
    , 0, 0, 0, 0, 0, 0 }


/* Ltpb__TimeStamp methods */
void   ltpb__time_stamp__init
                     (Ltpb__TimeStamp         *message);
size_t ltpb__time_stamp__get_packed_size
                     (const Ltpb__TimeStamp   *message);
size_t ltpb__time_stamp__pack
                     (const Ltpb__TimeStamp   *message,
                      uint8_t             *out);
size_t ltpb__time_stamp__pack_to_buffer
                     (const Ltpb__TimeStamp   *message,
                      ProtobufCBuffer     *buffer);
Ltpb__TimeStamp *
       ltpb__time_stamp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ltpb__time_stamp__free_unpacked
                     (Ltpb__TimeStamp *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Ltpb__TimeStamp_Closure)
                 (const Ltpb__TimeStamp *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor ltpb__time_stamp__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_time_5fstamp_2eproto__INCLUDED */
