/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: view_preferences.proto */

#ifndef PROTOBUF_C_view_5fpreferences_2eproto__INCLUDED
#define PROTOBUF_C_view_5fpreferences_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "point2f.pb-c.h"

typedef struct _Ltpb__ViewPreferences Ltpb__ViewPreferences;


/* --- enums --- */

typedef enum _Ltpb__ViewPreferences__HDRMode {
  LTPB__VIEW_PREFERENCES__HDRMODE__HDR_MODE_NONE = 0,
  LTPB__VIEW_PREFERENCES__HDRMODE__HDR_MODE_DEFAULT = 1,
  LTPB__VIEW_PREFERENCES__HDRMODE__HDR_MODE_NATURAL = 2,
  LTPB__VIEW_PREFERENCES__HDRMODE__HDR_MODE_SURREAL = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LTPB__VIEW_PREFERENCES__HDRMODE)
} Ltpb__ViewPreferences__HDRMode;
typedef enum _Ltpb__ViewPreferences__ViewPresets {
  LTPB__VIEW_PREFERENCES__VIEW_PRESETS__VIEW_PRESET_NONE = 0,
  LTPB__VIEW_PREFERENCES__VIEW_PRESETS__VIEW_PRESET_NATURAL = 1,
  LTPB__VIEW_PREFERENCES__VIEW_PRESETS__VIEW_PRESET_FAITHFUL = 2,
  LTPB__VIEW_PREFERENCES__VIEW_PRESETS__VIEW_PRESET_LANDSCAPE = 3,
  LTPB__VIEW_PREFERENCES__VIEW_PRESETS__VIEW_PRESET_PORTRAIT = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LTPB__VIEW_PREFERENCES__VIEW_PRESETS)
} Ltpb__ViewPreferences__ViewPresets;
typedef enum _Ltpb__ViewPreferences__SceneMode {
  LTPB__VIEW_PREFERENCES__SCENE_MODE__SCENE_MODE_PORTRAIT = 0,
  LTPB__VIEW_PREFERENCES__SCENE_MODE__SCENE_MODE_LANDSCAPE = 1,
  LTPB__VIEW_PREFERENCES__SCENE_MODE__SCENE_MODE_SPORT = 2,
  LTPB__VIEW_PREFERENCES__SCENE_MODE__SCENE_MODE_MACRO = 3,
  LTPB__VIEW_PREFERENCES__SCENE_MODE__SCENE_MODE_NIGHT = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LTPB__VIEW_PREFERENCES__SCENE_MODE)
} Ltpb__ViewPreferences__SceneMode;
typedef enum _Ltpb__ViewPreferences__AWBMode {
  LTPB__VIEW_PREFERENCES__AWBMODE__AWB_MODE_AUTO = 0,
  LTPB__VIEW_PREFERENCES__AWBMODE__AWB_MODE_DAYLIGHT = 1,
  LTPB__VIEW_PREFERENCES__AWBMODE__AWB_MODE_SHADE = 2,
  LTPB__VIEW_PREFERENCES__AWBMODE__AWB_MODE_CLOUDY = 3,
  LTPB__VIEW_PREFERENCES__AWBMODE__AWB_MODE_TUNGSTEN = 4,
  LTPB__VIEW_PREFERENCES__AWBMODE__AWB_MODE_FLUORESCENT = 5,
  LTPB__VIEW_PREFERENCES__AWBMODE__AWB_MODE_FLASH = 6,
  LTPB__VIEW_PREFERENCES__AWBMODE__AWB_MODE_CUSTOM = 7,
  /*
   * same as AWB_MODE_CUSTOM but tint is estimated automatically.
   */
  LTPB__VIEW_PREFERENCES__AWBMODE__AWB_MODE_KELVIN = 8
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LTPB__VIEW_PREFERENCES__AWBMODE)
} Ltpb__ViewPreferences__AWBMode;

/* --- messages --- */

struct  _Ltpb__ViewPreferences
{
  ProtobufCMessage base;
  /*
   * Preferred f-number when doing synthetic DoF.
   */
  protobuf_c_boolean has_f_number;
  float f_number;
  /*
   * Exposure value shift of the rendered image .
   */
  protobuf_c_boolean has_ev_offset;
  float ev_offset;
  /*
   * If set to true the image will be rendered at native sensor resolution (e.g. not 16:9 crop)
   */
  protobuf_c_boolean has_disable_cropping;
  protobuf_c_boolean disable_cropping;
  /*
   * Controls the HDR TMO.
   */
  protobuf_c_boolean has_hdr_mode;
  Ltpb__ViewPreferences__HDRMode hdr_mode;
  /*
   * Controls the color rendering.
   */
  protobuf_c_boolean has_view_preset;
  Ltpb__ViewPreferences__ViewPresets view_preset;
  /*
   * Hint from 3A scene mode.
   */
  protobuf_c_boolean has_scene_mode;
  Ltpb__ViewPreferences__SceneMode scene_mode;
  /*
   * Hint from 3A for white-balance estimation algorithm.    
   */
  protobuf_c_boolean has_awb_mode;
  Ltpb__ViewPreferences__AWBMode awb_mode;
  /*
   * This holds the netural white XY coordinates if awb_mode is AWB_MODE_CUSTOM or AWB_MODE_KELVIN.
   */
  Ltpb__Point2F *awb_neutral_xy;
};
#define LTPB__VIEW_PREFERENCES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ltpb__view_preferences__descriptor) \
    , 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, NULL }


/* Ltpb__ViewPreferences methods */
void   ltpb__view_preferences__init
                     (Ltpb__ViewPreferences         *message);
size_t ltpb__view_preferences__get_packed_size
                     (const Ltpb__ViewPreferences   *message);
size_t ltpb__view_preferences__pack
                     (const Ltpb__ViewPreferences   *message,
                      uint8_t             *out);
size_t ltpb__view_preferences__pack_to_buffer
                     (const Ltpb__ViewPreferences   *message,
                      ProtobufCBuffer     *buffer);
Ltpb__ViewPreferences *
       ltpb__view_preferences__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ltpb__view_preferences__free_unpacked
                     (Ltpb__ViewPreferences *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Ltpb__ViewPreferences_Closure)
                 (const Ltpb__ViewPreferences *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor ltpb__view_preferences__descriptor;
extern const ProtobufCEnumDescriptor    ltpb__view_preferences__hdrmode__descriptor;
extern const ProtobufCEnumDescriptor    ltpb__view_preferences__view_presets__descriptor;
extern const ProtobufCEnumDescriptor    ltpb__view_preferences__scene_mode__descriptor;
extern const ProtobufCEnumDescriptor    ltpb__view_preferences__awbmode__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_view_5fpreferences_2eproto__INCLUDED */
