/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: color_calibration.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif
#include "sections.h"
#include "color_calibration.pb-c.h"
LIGHT_HEADER_FUNC void   ltpb__color_calibration__init
                     (Ltpb__ColorCalibration         *message)
{
  LIGHT_HEADER_STATIC static Ltpb__ColorCalibration init_value = LTPB__COLOR_CALIBRATION__INIT;
  *message = init_value;
}
LIGHT_HEADER_FUNC size_t ltpb__color_calibration__get_packed_size
                     (const Ltpb__ColorCalibration *message)
{
  assert(message->base.descriptor == &ltpb__color_calibration__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
LIGHT_HEADER_FUNC size_t ltpb__color_calibration__pack
                     (const Ltpb__ColorCalibration *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ltpb__color_calibration__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
LIGHT_HEADER_FUNC size_t ltpb__color_calibration__pack_to_buffer
                     (const Ltpb__ColorCalibration *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ltpb__color_calibration__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LIGHT_HEADER_FUNC Ltpb__ColorCalibration *
       ltpb__color_calibration__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ltpb__ColorCalibration *)
     protobuf_c_message_unpack (&ltpb__color_calibration__descriptor,
                                allocator, len, data);
}
LIGHT_HEADER_FUNC void   ltpb__color_calibration__free_unpacked
                     (Ltpb__ColorCalibration *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ltpb__color_calibration__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
LIGHT_HEADER_CONST static const ProtobufCEnumValue ltpb__color_calibration__illuminant_type__enum_values_by_number[9] =
{
  { "A", "LTPB__COLOR_CALIBRATION__ILLUMINANT_TYPE__A", 0 },
  { "D50", "LTPB__COLOR_CALIBRATION__ILLUMINANT_TYPE__D50", 1 },
  { "D65", "LTPB__COLOR_CALIBRATION__ILLUMINANT_TYPE__D65", 2 },
  { "D75", "LTPB__COLOR_CALIBRATION__ILLUMINANT_TYPE__D75", 3 },
  { "F2", "LTPB__COLOR_CALIBRATION__ILLUMINANT_TYPE__F2", 4 },
  { "F7", "LTPB__COLOR_CALIBRATION__ILLUMINANT_TYPE__F7", 5 },
  { "F11", "LTPB__COLOR_CALIBRATION__ILLUMINANT_TYPE__F11", 6 },
  { "TL84", "LTPB__COLOR_CALIBRATION__ILLUMINANT_TYPE__TL84", 7 },
  { "UNKNOWN", "LTPB__COLOR_CALIBRATION__ILLUMINANT_TYPE__UNKNOWN", 99 },
};
LIGHT_HEADER_CONST static const ProtobufCIntRange ltpb__color_calibration__illuminant_type__value_ranges[] = {
{0, 0},{99, 8},{0, 9}
};
LIGHT_HEADER_CONST static const ProtobufCEnumValueIndex ltpb__color_calibration__illuminant_type__enum_values_by_name[9] =
{
  { "A", 0 },
  { "D50", 1 },
  { "D65", 2 },
  { "D75", 3 },
  { "F11", 6 },
  { "F2", 4 },
  { "F7", 5 },
  { "TL84", 7 },
  { "UNKNOWN", 8 },
};
LIGHT_HEADER_CONST const ProtobufCEnumDescriptor ltpb__color_calibration__illuminant_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ltpb.ColorCalibration.IlluminantType",
  "IlluminantType",
  "Ltpb__ColorCalibration__IlluminantType",
  "ltpb",
  9,
  ltpb__color_calibration__illuminant_type__enum_values_by_number,
  9,
  ltpb__color_calibration__illuminant_type__enum_values_by_name,
  2,
  ltpb__color_calibration__illuminant_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
LIGHT_HEADER_CONST static const ProtobufCFieldDescriptor ltpb__color_calibration__field_descriptors[7] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Ltpb__ColorCalibration, type),
    &ltpb__color_calibration__illuminant_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "forward_matrix",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ltpb__ColorCalibration, forward_matrix),
    &ltpb__matrix3x3_f__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "color_matrix",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ltpb__ColorCalibration, color_matrix),
    &ltpb__matrix3x3_f__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rg_ratio",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Ltpb__ColorCalibration, rg_ratio),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bg_ratio",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Ltpb__ColorCalibration, bg_ratio),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "macbeth_data",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ltpb__ColorCalibration, n_macbeth_data),
    offsetof(Ltpb__ColorCalibration, macbeth_data),
    &ltpb__point3_f__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "illuminant_spd",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ltpb__ColorCalibration, n_illuminant_spd),
    offsetof(Ltpb__ColorCalibration, illuminant_spd),
    &ltpb__point2_f__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
LIGHT_HEADER_CONST static const unsigned ltpb__color_calibration__field_indices_by_name[] = {
  4,   /* field[4] = bg_ratio */
  2,   /* field[2] = color_matrix */
  1,   /* field[1] = forward_matrix */
  6,   /* field[6] = illuminant_spd */
  5,   /* field[5] = macbeth_data */
  3,   /* field[3] = rg_ratio */
  0,   /* field[0] = type */
};
LIGHT_HEADER_CONST static const ProtobufCIntRange ltpb__color_calibration__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
LIGHT_HEADER_CONST const ProtobufCMessageDescriptor ltpb__color_calibration__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ltpb.ColorCalibration",
  "ColorCalibration",
  "Ltpb__ColorCalibration",
  "ltpb",
  sizeof(Ltpb__ColorCalibration),
  7,
  ltpb__color_calibration__field_descriptors,
  ltpb__color_calibration__field_indices_by_name,
  1,  ltpb__color_calibration__number_ranges,
  (ProtobufCMessageInit) ltpb__color_calibration__init,
  NULL,NULL,NULL    /* reserved[123] */
};
