/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: geometric_calibration.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif
#include "sections.h"
#include "geometric_calibration.pb-c.h"
LIGHT_HEADER_FUNC void   ltpb__geometric_calibration__intrinsics__init
                     (Ltpb__GeometricCalibration__Intrinsics         *message)
{
  LIGHT_HEADER_STATIC static Ltpb__GeometricCalibration__Intrinsics init_value = LTPB__GEOMETRIC_CALIBRATION__INTRINSICS__INIT;
  *message = init_value;
}
LIGHT_HEADER_FUNC void   ltpb__geometric_calibration__extrinsics__canonical_format__init
                     (Ltpb__GeometricCalibration__Extrinsics__CanonicalFormat         *message)
{
  LIGHT_HEADER_STATIC static Ltpb__GeometricCalibration__Extrinsics__CanonicalFormat init_value = LTPB__GEOMETRIC_CALIBRATION__EXTRINSICS__CANONICAL_FORMAT__INIT;
  *message = init_value;
}
LIGHT_HEADER_FUNC void   ltpb__geometric_calibration__extrinsics__movable_mirror_format__init
                     (Ltpb__GeometricCalibration__Extrinsics__MovableMirrorFormat         *message)
{
  LIGHT_HEADER_STATIC static Ltpb__GeometricCalibration__Extrinsics__MovableMirrorFormat init_value = LTPB__GEOMETRIC_CALIBRATION__EXTRINSICS__MOVABLE_MIRROR_FORMAT__INIT;
  *message = init_value;
}
LIGHT_HEADER_FUNC void   ltpb__geometric_calibration__extrinsics__init
                     (Ltpb__GeometricCalibration__Extrinsics         *message)
{
  LIGHT_HEADER_STATIC static Ltpb__GeometricCalibration__Extrinsics init_value = LTPB__GEOMETRIC_CALIBRATION__EXTRINSICS__INIT;
  *message = init_value;
}
LIGHT_HEADER_FUNC void   ltpb__geometric_calibration__calibration_focus_bundle__init
                     (Ltpb__GeometricCalibration__CalibrationFocusBundle         *message)
{
  LIGHT_HEADER_STATIC static Ltpb__GeometricCalibration__CalibrationFocusBundle init_value = LTPB__GEOMETRIC_CALIBRATION__CALIBRATION_FOCUS_BUNDLE__INIT;
  *message = init_value;
}
LIGHT_HEADER_FUNC void   ltpb__geometric_calibration__angle_optical_center_mapping__init
                     (Ltpb__GeometricCalibration__AngleOpticalCenterMapping         *message)
{
  static Ltpb__GeometricCalibration__AngleOpticalCenterMapping init_value = LTPB__GEOMETRIC_CALIBRATION__ANGLE_OPTICAL_CENTER_MAPPING__INIT;
  *message = init_value;
}
LIGHT_HEADER_FUNC void   ltpb__geometric_calibration__init
                     (Ltpb__GeometricCalibration         *message)
{
  LIGHT_HEADER_STATIC static Ltpb__GeometricCalibration init_value = LTPB__GEOMETRIC_CALIBRATION__INIT;
  *message = init_value;
}
LIGHT_HEADER_FUNC size_t ltpb__geometric_calibration__get_packed_size
                     (const Ltpb__GeometricCalibration *message)
{
  assert(message->base.descriptor == &ltpb__geometric_calibration__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
LIGHT_HEADER_FUNC size_t ltpb__geometric_calibration__pack
                     (const Ltpb__GeometricCalibration *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ltpb__geometric_calibration__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
LIGHT_HEADER_FUNC size_t ltpb__geometric_calibration__pack_to_buffer
                     (const Ltpb__GeometricCalibration *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ltpb__geometric_calibration__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LIGHT_HEADER_FUNC Ltpb__GeometricCalibration *
       ltpb__geometric_calibration__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ltpb__GeometricCalibration *)
     protobuf_c_message_unpack (&ltpb__geometric_calibration__descriptor,
                                allocator, len, data);
}
LIGHT_HEADER_FUNC void   ltpb__geometric_calibration__free_unpacked
                     (Ltpb__GeometricCalibration *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ltpb__geometric_calibration__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
LIGHT_HEADER_CONST static const ProtobufCFieldDescriptor ltpb__geometric_calibration__intrinsics__field_descriptors[2] =
{
  {
    "k_mat",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ltpb__GeometricCalibration__Intrinsics, k_mat),
    &ltpb__matrix3x3_f__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rms_error",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Ltpb__GeometricCalibration__Intrinsics, has_rms_error),
    offsetof(Ltpb__GeometricCalibration__Intrinsics, rms_error),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
LIGHT_HEADER_CONST static const unsigned ltpb__geometric_calibration__intrinsics__field_indices_by_name[] = {
  0,   /* field[0] = k_mat */
  1,   /* field[1] = rms_error */
};
LIGHT_HEADER_CONST static const ProtobufCIntRange ltpb__geometric_calibration__intrinsics__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
LIGHT_HEADER_CONST const ProtobufCMessageDescriptor ltpb__geometric_calibration__intrinsics__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ltpb.GeometricCalibration.Intrinsics",
  "Intrinsics",
  "Ltpb__GeometricCalibration__Intrinsics",
  "ltpb",
  sizeof(Ltpb__GeometricCalibration__Intrinsics),
  2,
  ltpb__geometric_calibration__intrinsics__field_descriptors,
  ltpb__geometric_calibration__intrinsics__field_indices_by_name,
  1,  ltpb__geometric_calibration__intrinsics__number_ranges,
  (ProtobufCMessageInit) ltpb__geometric_calibration__intrinsics__init,
  NULL,NULL,NULL    /* reserved[123] */
};
LIGHT_HEADER_CONST static const ProtobufCFieldDescriptor ltpb__geometric_calibration__extrinsics__canonical_format__field_descriptors[4] =
{
  {
    "rotation",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ltpb__GeometricCalibration__Extrinsics__CanonicalFormat, rotation),
    &ltpb__matrix3x3_f__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "translation",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ltpb__GeometricCalibration__Extrinsics__CanonicalFormat, translation),
    &ltpb__point3_f__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stereo_error",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Ltpb__GeometricCalibration__Extrinsics__CanonicalFormat, has_stereo_error),
    offsetof(Ltpb__GeometricCalibration__Extrinsics__CanonicalFormat, stereo_error),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reprojection_error",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Ltpb__GeometricCalibration__Extrinsics__CanonicalFormat, has_reprojection_error),
    offsetof(Ltpb__GeometricCalibration__Extrinsics__CanonicalFormat, reprojection_error),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
LIGHT_HEADER_CONST static const unsigned ltpb__geometric_calibration__extrinsics__canonical_format__field_indices_by_name[] = {
  3,   /* field[3] = reprojection_error */
  0,   /* field[0] = rotation */
  2,   /* field[2] = stereo_error */
  1,   /* field[1] = translation */
};
LIGHT_HEADER_CONST static const ProtobufCIntRange ltpb__geometric_calibration__extrinsics__canonical_format__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
LIGHT_HEADER_CONST const ProtobufCMessageDescriptor ltpb__geometric_calibration__extrinsics__canonical_format__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ltpb.GeometricCalibration.Extrinsics.CanonicalFormat",
  "CanonicalFormat",
  "Ltpb__GeometricCalibration__Extrinsics__CanonicalFormat",
  "ltpb",
  sizeof(Ltpb__GeometricCalibration__Extrinsics__CanonicalFormat),
  4,
  ltpb__geometric_calibration__extrinsics__canonical_format__field_descriptors,
  ltpb__geometric_calibration__extrinsics__canonical_format__field_indices_by_name,
  1,  ltpb__geometric_calibration__extrinsics__canonical_format__number_ranges,
  (ProtobufCMessageInit) ltpb__geometric_calibration__extrinsics__canonical_format__init,
  NULL,NULL,NULL    /* reserved[123] */
};
LIGHT_HEADER_CONST static const ProtobufCFieldDescriptor ltpb__geometric_calibration__extrinsics__movable_mirror_format__field_descriptors[2] =
{
  {
    "mirror_system",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ltpb__GeometricCalibration__Extrinsics__MovableMirrorFormat, mirror_system),
    &ltpb__mirror_system__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mirror_actuator_mapping",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ltpb__GeometricCalibration__Extrinsics__MovableMirrorFormat, mirror_actuator_mapping),
    &ltpb__mirror_actuator_mapping__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
LIGHT_HEADER_CONST static const unsigned ltpb__geometric_calibration__extrinsics__movable_mirror_format__field_indices_by_name[] = {
  1,   /* field[1] = mirror_actuator_mapping */
  0,   /* field[0] = mirror_system */
};
LIGHT_HEADER_CONST static const ProtobufCIntRange ltpb__geometric_calibration__extrinsics__movable_mirror_format__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
LIGHT_HEADER_CONST const ProtobufCMessageDescriptor ltpb__geometric_calibration__extrinsics__movable_mirror_format__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ltpb.GeometricCalibration.Extrinsics.MovableMirrorFormat",
  "MovableMirrorFormat",
  "Ltpb__GeometricCalibration__Extrinsics__MovableMirrorFormat",
  "ltpb",
  sizeof(Ltpb__GeometricCalibration__Extrinsics__MovableMirrorFormat),
  2,
  ltpb__geometric_calibration__extrinsics__movable_mirror_format__field_descriptors,
  ltpb__geometric_calibration__extrinsics__movable_mirror_format__field_indices_by_name,
  1,  ltpb__geometric_calibration__extrinsics__movable_mirror_format__number_ranges,
  (ProtobufCMessageInit) ltpb__geometric_calibration__extrinsics__movable_mirror_format__init,
  NULL,NULL,NULL    /* reserved[123] */
};
LIGHT_HEADER_CONST static const ProtobufCFieldDescriptor ltpb__geometric_calibration__extrinsics__field_descriptors[2] =
{
  {
    "canonical",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ltpb__GeometricCalibration__Extrinsics, canonical),
    &ltpb__geometric_calibration__extrinsics__canonical_format__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "moveable_mirror",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ltpb__GeometricCalibration__Extrinsics, moveable_mirror),
    &ltpb__geometric_calibration__extrinsics__movable_mirror_format__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
LIGHT_HEADER_CONST static const unsigned ltpb__geometric_calibration__extrinsics__field_indices_by_name[] = {
  0,   /* field[0] = canonical */
  1,   /* field[1] = moveable_mirror */
};
LIGHT_HEADER_CONST static const ProtobufCIntRange ltpb__geometric_calibration__extrinsics__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
LIGHT_HEADER_CONST const ProtobufCMessageDescriptor ltpb__geometric_calibration__extrinsics__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ltpb.GeometricCalibration.Extrinsics",
  "Extrinsics",
  "Ltpb__GeometricCalibration__Extrinsics",
  "ltpb",
  sizeof(Ltpb__GeometricCalibration__Extrinsics),
  2,
  ltpb__geometric_calibration__extrinsics__field_descriptors,
  ltpb__geometric_calibration__extrinsics__field_indices_by_name,
  1,  ltpb__geometric_calibration__extrinsics__number_ranges,
  (ProtobufCMessageInit) ltpb__geometric_calibration__extrinsics__init,
  NULL,NULL,NULL    /* reserved[123] */
};
LIGHT_HEADER_CONST static const ProtobufCFieldDescriptor ltpb__geometric_calibration__calibration_focus_bundle__field_descriptors[5] =
{
  {
    "focus_distance",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Ltpb__GeometricCalibration__CalibrationFocusBundle, focus_distance),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "intrinsics",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ltpb__GeometricCalibration__CalibrationFocusBundle, intrinsics),
    &ltpb__geometric_calibration__intrinsics__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "extrinsics",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ltpb__GeometricCalibration__CalibrationFocusBundle, extrinsics),
    &ltpb__geometric_calibration__extrinsics__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sensor_temp",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(Ltpb__GeometricCalibration__CalibrationFocusBundle, has_sensor_temp),
    offsetof(Ltpb__GeometricCalibration__CalibrationFocusBundle, sensor_temp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_temp",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ltpb__GeometricCalibration__CalibrationFocusBundle, device_temp),
    &ltpb__device_temp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
LIGHT_HEADER_CONST static const unsigned ltpb__geometric_calibration__calibration_focus_bundle__field_indices_by_name[] = {
  4,   /* field[4] = device_temp */
  2,   /* field[2] = extrinsics */
  0,   /* field[0] = focus_distance */
  1,   /* field[1] = intrinsics */
  3,   /* field[3] = sensor_temp */
};
LIGHT_HEADER_CONST static const ProtobufCIntRange ltpb__geometric_calibration__calibration_focus_bundle__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
LIGHT_HEADER_CONST const ProtobufCMessageDescriptor ltpb__geometric_calibration__calibration_focus_bundle__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ltpb.GeometricCalibration.CalibrationFocusBundle",
  "CalibrationFocusBundle",
  "Ltpb__GeometricCalibration__CalibrationFocusBundle",
  "ltpb",
  sizeof(Ltpb__GeometricCalibration__CalibrationFocusBundle),
  5,
  ltpb__geometric_calibration__calibration_focus_bundle__field_descriptors,
  ltpb__geometric_calibration__calibration_focus_bundle__field_indices_by_name,
  1,  ltpb__geometric_calibration__calibration_focus_bundle__number_ranges,
  (ProtobufCMessageInit) ltpb__geometric_calibration__calibration_focus_bundle__init,
  NULL,NULL,NULL    /* reserved[123] */
};
LIGHT_HEADER_CONST static const ProtobufCFieldDescriptor ltpb__geometric_calibration__angle_optical_center_mapping__field_descriptors[5] =
{
  {
    "center_start",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ltpb__GeometricCalibration__AngleOpticalCenterMapping, center_start),
    &ltpb__point2_f__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "center_end",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ltpb__GeometricCalibration__AngleOpticalCenterMapping, center_end),
    &ltpb__point2_f__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "angle_offset",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Ltpb__GeometricCalibration__AngleOpticalCenterMapping, angle_offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "t_scale",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Ltpb__GeometricCalibration__AngleOpticalCenterMapping, t_scale),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "t_offset",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Ltpb__GeometricCalibration__AngleOpticalCenterMapping, t_offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
LIGHT_HEADER_CONST static const unsigned ltpb__geometric_calibration__angle_optical_center_mapping__field_indices_by_name[] = {
  2,   /* field[2] = angle_offset */
  1,   /* field[1] = center_end */
  0,   /* field[0] = center_start */
  4,   /* field[4] = t_offset */
  3,   /* field[3] = t_scale */
};
LIGHT_HEADER_CONST static const ProtobufCIntRange ltpb__geometric_calibration__angle_optical_center_mapping__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
LIGHT_HEADER_CONST const ProtobufCMessageDescriptor ltpb__geometric_calibration__angle_optical_center_mapping__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ltpb.GeometricCalibration.AngleOpticalCenterMapping",
  "AngleOpticalCenterMapping",
  "Ltpb__GeometricCalibration__AngleOpticalCenterMapping",
  "ltpb",
  sizeof(Ltpb__GeometricCalibration__AngleOpticalCenterMapping),
  5,
  ltpb__geometric_calibration__angle_optical_center_mapping__field_descriptors,
  ltpb__geometric_calibration__angle_optical_center_mapping__field_indices_by_name,
  1,  ltpb__geometric_calibration__angle_optical_center_mapping__number_ranges,
  (ProtobufCMessageInit) ltpb__geometric_calibration__angle_optical_center_mapping__init,
  NULL,NULL,NULL    /* reserved[123] */
};
LIGHT_HEADER_CONST static const ProtobufCEnumValue ltpb__geometric_calibration__mirror_type__enum_values_by_number[3] =
{
  { "NONE", "LTPB__GEOMETRIC_CALIBRATION__MIRROR_TYPE__NONE", 0 },
  { "GLUED", "LTPB__GEOMETRIC_CALIBRATION__MIRROR_TYPE__GLUED", 1 },
  { "MOVABLE", "LTPB__GEOMETRIC_CALIBRATION__MIRROR_TYPE__MOVABLE", 2 },
};
LIGHT_HEADER_CONST static const ProtobufCIntRange ltpb__geometric_calibration__mirror_type__value_ranges[] = {
{0, 0},{0, 3}
};
LIGHT_HEADER_CONST static const ProtobufCEnumValueIndex ltpb__geometric_calibration__mirror_type__enum_values_by_name[3] =
{
  { "GLUED", 1 },
  { "MOVABLE", 2 },
  { "NONE", 0 },
};
LIGHT_HEADER_CONST const ProtobufCEnumDescriptor ltpb__geometric_calibration__mirror_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ltpb.GeometricCalibration.MirrorType",
  "MirrorType",
  "Ltpb__GeometricCalibration__MirrorType",
  "ltpb",
  3,
  ltpb__geometric_calibration__mirror_type__enum_values_by_number,
  3,
  ltpb__geometric_calibration__mirror_type__enum_values_by_name,
  1,
  ltpb__geometric_calibration__mirror_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
LIGHT_HEADER_CONST static const ProtobufCFieldDescriptor ltpb__geometric_calibration__field_descriptors[6] =
{
  {
    "mirror_type",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Ltpb__GeometricCalibration, has_mirror_type),
    offsetof(Ltpb__GeometricCalibration, mirror_type),
    &ltpb__geometric_calibration__mirror_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "per_focus_calibration",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ltpb__GeometricCalibration, n_per_focus_calibration),
    offsetof(Ltpb__GeometricCalibration, per_focus_calibration),
    &ltpb__geometric_calibration__calibration_focus_bundle__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "distortion",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ltpb__GeometricCalibration, distortion),
    &ltpb__distortion__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lens_hall_code_range",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ltpb__GeometricCalibration, lens_hall_code_range),
    &ltpb__range2_f__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "focus_distance_range",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ltpb__GeometricCalibration, focus_distance_range),
    &ltpb__range2_f__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "angle_optical_center_mapping",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ltpb__GeometricCalibration, angle_optical_center_mapping),
    &ltpb__geometric_calibration__angle_optical_center_mapping__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
LIGHT_HEADER_CONST static const unsigned ltpb__geometric_calibration__field_indices_by_name[] = {
  5,   /* field[5] = angle_optical_center_mapping */
  2,   /* field[2] = distortion */
  4,   /* field[4] = focus_distance_range */
  3,   /* field[3] = lens_hall_code_range */
  0,   /* field[0] = mirror_type */
  1,   /* field[1] = per_focus_calibration */
};
LIGHT_HEADER_CONST static const ProtobufCIntRange ltpb__geometric_calibration__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
LIGHT_HEADER_CONST const ProtobufCMessageDescriptor ltpb__geometric_calibration__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ltpb.GeometricCalibration",
  "GeometricCalibration",
  "Ltpb__GeometricCalibration",
  "ltpb",
  sizeof(Ltpb__GeometricCalibration),
  6,
  ltpb__geometric_calibration__field_descriptors,
  ltpb__geometric_calibration__field_indices_by_name,
  1,  ltpb__geometric_calibration__number_ranges,
  (ProtobufCMessageInit) ltpb__geometric_calibration__init,
  NULL,NULL,NULL    /* reserved[123] */
};
