/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: matrix3x3f.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif
#include "sections.h"
#include "matrix3x3f.pb-c.h"
LIGHT_HEADER_FUNC void   ltpb__matrix3x3_f__init
                     (Ltpb__Matrix3x3F         *message)
{
  LIGHT_HEADER_STATIC static Ltpb__Matrix3x3F init_value = LTPB__MATRIX3X3_F__INIT;
  *message = init_value;
}
LIGHT_HEADER_FUNC size_t ltpb__matrix3x3_f__get_packed_size
                     (const Ltpb__Matrix3x3F *message)
{
  assert(message->base.descriptor == &ltpb__matrix3x3_f__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
LIGHT_HEADER_FUNC size_t ltpb__matrix3x3_f__pack
                     (const Ltpb__Matrix3x3F *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ltpb__matrix3x3_f__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
LIGHT_HEADER_FUNC size_t ltpb__matrix3x3_f__pack_to_buffer
                     (const Ltpb__Matrix3x3F *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ltpb__matrix3x3_f__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LIGHT_HEADER_FUNC Ltpb__Matrix3x3F *
       ltpb__matrix3x3_f__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ltpb__Matrix3x3F *)
     protobuf_c_message_unpack (&ltpb__matrix3x3_f__descriptor,
                                allocator, len, data);
}
LIGHT_HEADER_FUNC void   ltpb__matrix3x3_f__free_unpacked
                     (Ltpb__Matrix3x3F *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ltpb__matrix3x3_f__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
LIGHT_HEADER_CONST static const ProtobufCFieldDescriptor ltpb__matrix3x3_f__field_descriptors[9] =
{
  {
    "x00",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Ltpb__Matrix3x3F, x00),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "x01",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Ltpb__Matrix3x3F, x01),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "x02",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Ltpb__Matrix3x3F, x02),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "x10",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Ltpb__Matrix3x3F, x10),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "x11",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Ltpb__Matrix3x3F, x11),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "x12",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Ltpb__Matrix3x3F, x12),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "x20",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Ltpb__Matrix3x3F, x20),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "x21",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Ltpb__Matrix3x3F, x21),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "x22",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Ltpb__Matrix3x3F, x22),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
LIGHT_HEADER_CONST static const unsigned ltpb__matrix3x3_f__field_indices_by_name[] = {
  0,   /* field[0] = x00 */
  1,   /* field[1] = x01 */
  2,   /* field[2] = x02 */
  3,   /* field[3] = x10 */
  4,   /* field[4] = x11 */
  5,   /* field[5] = x12 */
  6,   /* field[6] = x20 */
  7,   /* field[7] = x21 */
  8,   /* field[8] = x22 */
};
LIGHT_HEADER_CONST static const ProtobufCIntRange ltpb__matrix3x3_f__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
LIGHT_HEADER_CONST const ProtobufCMessageDescriptor ltpb__matrix3x3_f__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ltpb.Matrix3x3F",
  "Matrix3x3F",
  "Ltpb__Matrix3x3F",
  "ltpb",
  sizeof(Ltpb__Matrix3x3F),
  9,
  ltpb__matrix3x3_f__field_descriptors,
  ltpb__matrix3x3_f__field_indices_by_name,
  1,  ltpb__matrix3x3_f__number_ranges,
  (ProtobufCMessageInit) ltpb__matrix3x3_f__init,
  NULL,NULL,NULL    /* reserved[123] */
};
