/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proximity_sensors.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "proximity_sensors.pb-c.h"
#include "sections.h"

LIGHT_HEADER_FUNC void   ltpb__proximity_sensors__init
                     (Ltpb__ProximitySensors         *message)
{
  LIGHT_HEADER_STATIC static Ltpb__ProximitySensors init_value = LTPB__PROXIMITY_SENSORS__INIT;
  *message = init_value;
}
LIGHT_HEADER_FUNC size_t ltpb__proximity_sensors__get_packed_size
                     (const Ltpb__ProximitySensors *message)
{
  assert(message->base.descriptor == &ltpb__proximity_sensors__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
LIGHT_HEADER_FUNC size_t ltpb__proximity_sensors__pack
                     (const Ltpb__ProximitySensors *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ltpb__proximity_sensors__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
LIGHT_HEADER_FUNC size_t ltpb__proximity_sensors__pack_to_buffer
                     (const Ltpb__ProximitySensors *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ltpb__proximity_sensors__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LIGHT_HEADER_FUNC Ltpb__ProximitySensors *
       ltpb__proximity_sensors__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ltpb__ProximitySensors *)
     protobuf_c_message_unpack (&ltpb__proximity_sensors__descriptor,
                                allocator, len, data);
}
LIGHT_HEADER_FUNC void   ltpb__proximity_sensors__free_unpacked
                     (Ltpb__ProximitySensors *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ltpb__proximity_sensors__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
LIGHT_HEADER_CONST static const ProtobufCFieldDescriptor ltpb__proximity_sensors__field_descriptors[5] =
{
  {
    "sensor_1",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Ltpb__ProximitySensors, sensor_1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sensor_2",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Ltpb__ProximitySensors, sensor_2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sensor_3",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Ltpb__ProximitySensors, sensor_3),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sensor_4",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Ltpb__ProximitySensors, sensor_4),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sensor_5",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Ltpb__ProximitySensors, sensor_5),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
LIGHT_HEADER_CONST static const unsigned ltpb__proximity_sensors__field_indices_by_name[] = {
  0,   /* field[0] = sensor_1 */
  1,   /* field[1] = sensor_2 */
  2,   /* field[2] = sensor_3 */
  3,   /* field[3] = sensor_4 */
  4,   /* field[4] = sensor_5 */
};
LIGHT_HEADER_CONST static const ProtobufCIntRange ltpb__proximity_sensors__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
LIGHT_HEADER_CONST const ProtobufCMessageDescriptor ltpb__proximity_sensors__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ltpb.ProximitySensors",
  "ProximitySensors",
  "Ltpb__ProximitySensors",
  "ltpb",
  sizeof(Ltpb__ProximitySensors),
  5,
  ltpb__proximity_sensors__field_descriptors,
  ltpb__proximity_sensors__field_indices_by_name,
  1,  ltpb__proximity_sensors__number_ranges,
  (ProtobufCMessageInit) ltpb__proximity_sensors__init,
  NULL,NULL,NULL    /* reserved[123] */
};
