/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: time_stamp.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif
#include "sections.h"
#include "time_stamp.pb-c.h"
LIGHT_HEADER_FUNC void   ltpb__time_stamp__init
                     (Ltpb__TimeStamp         *message)
{
  LIGHT_HEADER_STATIC static Ltpb__TimeStamp init_value = LTPB__TIME_STAMP__INIT;
  *message = init_value;
}
LIGHT_HEADER_FUNC size_t ltpb__time_stamp__get_packed_size
                     (const Ltpb__TimeStamp *message)
{
  assert(message->base.descriptor == &ltpb__time_stamp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
LIGHT_HEADER_FUNC size_t ltpb__time_stamp__pack
                     (const Ltpb__TimeStamp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ltpb__time_stamp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
LIGHT_HEADER_FUNC size_t ltpb__time_stamp__pack_to_buffer
                     (const Ltpb__TimeStamp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ltpb__time_stamp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LIGHT_HEADER_FUNC Ltpb__TimeStamp *
       ltpb__time_stamp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ltpb__TimeStamp *)
     protobuf_c_message_unpack (&ltpb__time_stamp__descriptor,
                                allocator, len, data);
}
LIGHT_HEADER_FUNC void   ltpb__time_stamp__free_unpacked
                     (Ltpb__TimeStamp *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ltpb__time_stamp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
LIGHT_HEADER_CONST static const ProtobufCFieldDescriptor ltpb__time_stamp__field_descriptors[6] =
{
  {
    "year",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Ltpb__TimeStamp, year),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "month",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Ltpb__TimeStamp, month),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "day",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Ltpb__TimeStamp, day),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hour",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Ltpb__TimeStamp, hour),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "minute",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Ltpb__TimeStamp, minute),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "second",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Ltpb__TimeStamp, second),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
LIGHT_HEADER_CONST static const unsigned ltpb__time_stamp__field_indices_by_name[] = {
  2,   /* field[2] = day */
  3,   /* field[3] = hour */
  4,   /* field[4] = minute */
  1,   /* field[1] = month */
  5,   /* field[5] = second */
  0,   /* field[0] = year */
};
LIGHT_HEADER_CONST static const ProtobufCIntRange ltpb__time_stamp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
LIGHT_HEADER_CONST const ProtobufCMessageDescriptor ltpb__time_stamp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ltpb.TimeStamp",
  "TimeStamp",
  "Ltpb__TimeStamp",
  "ltpb",
  sizeof(Ltpb__TimeStamp),
  6,
  ltpb__time_stamp__field_descriptors,
  ltpb__time_stamp__field_indices_by_name,
  1,  ltpb__time_stamp__number_ranges,
  (ProtobufCMessageInit) ltpb__time_stamp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
