/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: view_preferences.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "view_preferences.pb-c.h"
#include "sections.h"
LIGHT_HEADER_FUNC void   ltpb__view_preferences__init
                     (Ltpb__ViewPreferences         *message)
{
  LIGHT_HEADER_STATIC static Ltpb__ViewPreferences init_value = LTPB__VIEW_PREFERENCES__INIT;
  *message = init_value;
}
LIGHT_HEADER_FUNC size_t ltpb__view_preferences__get_packed_size
                     (const Ltpb__ViewPreferences *message)
{
  assert(message->base.descriptor == &ltpb__view_preferences__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
LIGHT_HEADER_FUNC size_t ltpb__view_preferences__pack
                     (const Ltpb__ViewPreferences *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ltpb__view_preferences__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
LIGHT_HEADER_FUNC size_t ltpb__view_preferences__pack_to_buffer
                     (const Ltpb__ViewPreferences *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ltpb__view_preferences__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LIGHT_HEADER_FUNC Ltpb__ViewPreferences *
       ltpb__view_preferences__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ltpb__ViewPreferences *)
     protobuf_c_message_unpack (&ltpb__view_preferences__descriptor,
                                allocator, len, data);
}
LIGHT_HEADER_FUNC void   ltpb__view_preferences__free_unpacked
                     (Ltpb__ViewPreferences *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ltpb__view_preferences__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
LIGHT_HEADER_CONST static const ProtobufCEnumValue ltpb__view_preferences__hdrmode__enum_values_by_number[4] =
{
  { "HDR_MODE_NONE", "LTPB__VIEW_PREFERENCES__HDRMODE__HDR_MODE_NONE", 0 },
  { "HDR_MODE_DEFAULT", "LTPB__VIEW_PREFERENCES__HDRMODE__HDR_MODE_DEFAULT", 1 },
  { "HDR_MODE_NATURAL", "LTPB__VIEW_PREFERENCES__HDRMODE__HDR_MODE_NATURAL", 2 },
  { "HDR_MODE_SURREAL", "LTPB__VIEW_PREFERENCES__HDRMODE__HDR_MODE_SURREAL", 3 },
};
LIGHT_HEADER_CONST static const ProtobufCIntRange ltpb__view_preferences__hdrmode__value_ranges[] = {
{0, 0},{0, 4}
};
LIGHT_HEADER_CONST static const ProtobufCEnumValueIndex ltpb__view_preferences__hdrmode__enum_values_by_name[4] =
{
  { "HDR_MODE_DEFAULT", 1 },
  { "HDR_MODE_NATURAL", 2 },
  { "HDR_MODE_NONE", 0 },
  { "HDR_MODE_SURREAL", 3 },
};
LIGHT_HEADER_CONST const ProtobufCEnumDescriptor ltpb__view_preferences__hdrmode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ltpb.ViewPreferences.HDRMode",
  "HDRMode",
  "Ltpb__ViewPreferences__HDRMode",
  "ltpb",
  4,
  ltpb__view_preferences__hdrmode__enum_values_by_number,
  4,
  ltpb__view_preferences__hdrmode__enum_values_by_name,
  1,
  ltpb__view_preferences__hdrmode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
LIGHT_HEADER_CONST static const ProtobufCEnumValue ltpb__view_preferences__view_presets__enum_values_by_number[5] =
{
  { "VIEW_PRESET_NONE", "LTPB__VIEW_PREFERENCES__VIEW_PRESETS__VIEW_PRESET_NONE", 0 },
  { "VIEW_PRESET_NATURAL", "LTPB__VIEW_PREFERENCES__VIEW_PRESETS__VIEW_PRESET_NATURAL", 1 },
  { "VIEW_PRESET_FAITHFUL", "LTPB__VIEW_PREFERENCES__VIEW_PRESETS__VIEW_PRESET_FAITHFUL", 2 },
  { "VIEW_PRESET_LANDSCAPE", "LTPB__VIEW_PREFERENCES__VIEW_PRESETS__VIEW_PRESET_LANDSCAPE", 3 },
  { "VIEW_PRESET_PORTRAIT", "LTPB__VIEW_PREFERENCES__VIEW_PRESETS__VIEW_PRESET_PORTRAIT", 4 },
};
LIGHT_HEADER_CONST static const ProtobufCIntRange ltpb__view_preferences__view_presets__value_ranges[] = {
{0, 0},{0, 5}
};
LIGHT_HEADER_CONST static const ProtobufCEnumValueIndex ltpb__view_preferences__view_presets__enum_values_by_name[5] =
{
  { "VIEW_PRESET_FAITHFUL", 2 },
  { "VIEW_PRESET_LANDSCAPE", 3 },
  { "VIEW_PRESET_NATURAL", 1 },
  { "VIEW_PRESET_NONE", 0 },
  { "VIEW_PRESET_PORTRAIT", 4 },
};
LIGHT_HEADER_CONST const ProtobufCEnumDescriptor ltpb__view_preferences__view_presets__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ltpb.ViewPreferences.ViewPresets",
  "ViewPresets",
  "Ltpb__ViewPreferences__ViewPresets",
  "ltpb",
  5,
  ltpb__view_preferences__view_presets__enum_values_by_number,
  5,
  ltpb__view_preferences__view_presets__enum_values_by_name,
  1,
  ltpb__view_preferences__view_presets__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
LIGHT_HEADER_CONST static const ProtobufCEnumValue ltpb__view_preferences__scene_mode__enum_values_by_number[5] =
{
  { "SCENE_MODE_PORTRAIT", "LTPB__VIEW_PREFERENCES__SCENE_MODE__SCENE_MODE_PORTRAIT", 0 },
  { "SCENE_MODE_LANDSCAPE", "LTPB__VIEW_PREFERENCES__SCENE_MODE__SCENE_MODE_LANDSCAPE", 1 },
  { "SCENE_MODE_SPORT", "LTPB__VIEW_PREFERENCES__SCENE_MODE__SCENE_MODE_SPORT", 2 },
  { "SCENE_MODE_MACRO", "LTPB__VIEW_PREFERENCES__SCENE_MODE__SCENE_MODE_MACRO", 3 },
  { "SCENE_MODE_NIGHT", "LTPB__VIEW_PREFERENCES__SCENE_MODE__SCENE_MODE_NIGHT", 4 },
};
LIGHT_HEADER_CONST static const ProtobufCIntRange ltpb__view_preferences__scene_mode__value_ranges[] = {
{0, 0},{0, 5}
};
LIGHT_HEADER_CONST static const ProtobufCEnumValueIndex ltpb__view_preferences__scene_mode__enum_values_by_name[5] =
{
  { "SCENE_MODE_LANDSCAPE", 1 },
  { "SCENE_MODE_MACRO", 3 },
  { "SCENE_MODE_NIGHT", 4 },
  { "SCENE_MODE_PORTRAIT", 0 },
  { "SCENE_MODE_SPORT", 2 },
};
LIGHT_HEADER_CONST const ProtobufCEnumDescriptor ltpb__view_preferences__scene_mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ltpb.ViewPreferences.SceneMode",
  "SceneMode",
  "Ltpb__ViewPreferences__SceneMode",
  "ltpb",
  5,
  ltpb__view_preferences__scene_mode__enum_values_by_number,
  5,
  ltpb__view_preferences__scene_mode__enum_values_by_name,
  1,
  ltpb__view_preferences__scene_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
LIGHT_HEADER_CONST static const ProtobufCEnumValue ltpb__view_preferences__awbmode__enum_values_by_number[9] =
{
  { "AWB_MODE_AUTO", "LTPB__VIEW_PREFERENCES__AWBMODE__AWB_MODE_AUTO", 0 },
  { "AWB_MODE_DAYLIGHT", "LTPB__VIEW_PREFERENCES__AWBMODE__AWB_MODE_DAYLIGHT", 1 },
  { "AWB_MODE_SHADE", "LTPB__VIEW_PREFERENCES__AWBMODE__AWB_MODE_SHADE", 2 },
  { "AWB_MODE_CLOUDY", "LTPB__VIEW_PREFERENCES__AWBMODE__AWB_MODE_CLOUDY", 3 },
  { "AWB_MODE_TUNGSTEN", "LTPB__VIEW_PREFERENCES__AWBMODE__AWB_MODE_TUNGSTEN", 4 },
  { "AWB_MODE_FLUORESCENT", "LTPB__VIEW_PREFERENCES__AWBMODE__AWB_MODE_FLUORESCENT", 5 },
  { "AWB_MODE_FLASH", "LTPB__VIEW_PREFERENCES__AWBMODE__AWB_MODE_FLASH", 6 },
  { "AWB_MODE_CUSTOM", "LTPB__VIEW_PREFERENCES__AWBMODE__AWB_MODE_CUSTOM", 7 },
  { "AWB_MODE_KELVIN", "LTPB__VIEW_PREFERENCES__AWBMODE__AWB_MODE_KELVIN", 8 },
};
LIGHT_HEADER_CONST static const ProtobufCIntRange ltpb__view_preferences__awbmode__value_ranges[] = {
{0, 0},{0, 9}
};
LIGHT_HEADER_CONST static const ProtobufCEnumValueIndex ltpb__view_preferences__awbmode__enum_values_by_name[9] =
{
  { "AWB_MODE_AUTO", 0 },
  { "AWB_MODE_CLOUDY", 3 },
  { "AWB_MODE_CUSTOM", 7 },
  { "AWB_MODE_DAYLIGHT", 1 },
  { "AWB_MODE_FLASH", 6 },
  { "AWB_MODE_FLUORESCENT", 5 },
  { "AWB_MODE_KELVIN", 8 },
  { "AWB_MODE_SHADE", 2 },
  { "AWB_MODE_TUNGSTEN", 4 },
};
LIGHT_HEADER_CONST const ProtobufCEnumDescriptor ltpb__view_preferences__awbmode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ltpb.ViewPreferences.AWBMode",
  "AWBMode",
  "Ltpb__ViewPreferences__AWBMode",
  "ltpb",
  9,
  ltpb__view_preferences__awbmode__enum_values_by_number,
  9,
  ltpb__view_preferences__awbmode__enum_values_by_name,
  1,
  ltpb__view_preferences__awbmode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
LIGHT_HEADER_CONST static const ProtobufCFieldDescriptor ltpb__view_preferences__field_descriptors[8] =
{
  {
    "f_number",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Ltpb__ViewPreferences, has_f_number),
    offsetof(Ltpb__ViewPreferences, f_number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ev_offset",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Ltpb__ViewPreferences, has_ev_offset),
    offsetof(Ltpb__ViewPreferences, ev_offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "disable_cropping",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Ltpb__ViewPreferences, has_disable_cropping),
    offsetof(Ltpb__ViewPreferences, disable_cropping),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hdr_mode",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Ltpb__ViewPreferences, has_hdr_mode),
    offsetof(Ltpb__ViewPreferences, hdr_mode),
    &ltpb__view_preferences__hdrmode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "view_preset",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Ltpb__ViewPreferences, has_view_preset),
    offsetof(Ltpb__ViewPreferences, view_preset),
    &ltpb__view_preferences__view_presets__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scene_mode",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Ltpb__ViewPreferences, has_scene_mode),
    offsetof(Ltpb__ViewPreferences, scene_mode),
    &ltpb__view_preferences__scene_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "awb_neutral_xy",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ltpb__ViewPreferences, awb_neutral_xy),
    &ltpb__point2_f__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "awb_mode",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Ltpb__ViewPreferences, has_awb_mode),
    offsetof(Ltpb__ViewPreferences, awb_mode),
    &ltpb__view_preferences__awbmode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
LIGHT_HEADER_CONST static const unsigned ltpb__view_preferences__field_indices_by_name[] = {
  7,   /* field[7] = awb_mode */
  6,   /* field[6] = awb_neutral_xy */
  2,   /* field[2] = disable_cropping */
  1,   /* field[1] = ev_offset */
  0,   /* field[0] = f_number */
  3,   /* field[3] = hdr_mode */
  5,   /* field[5] = scene_mode */
  4,   /* field[4] = view_preset */
};
LIGHT_HEADER_CONST static const ProtobufCIntRange ltpb__view_preferences__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
LIGHT_HEADER_CONST const ProtobufCMessageDescriptor ltpb__view_preferences__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ltpb.ViewPreferences",
  "ViewPreferences",
  "Ltpb__ViewPreferences",
  "ltpb",
  sizeof(Ltpb__ViewPreferences),
  8,
  ltpb__view_preferences__field_descriptors,
  ltpb__view_preferences__field_indices_by_name,
  1,  ltpb__view_preferences__number_ranges,
  (ProtobufCMessageInit) ltpb__view_preferences__init,
  NULL,NULL,NULL    /* reserved[123] */
};
