/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: camera_id.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif
#include "sections.h"
#include "camera_id.pb-c.h"
LIGHT_HEADER_CONST static const ProtobufCEnumValue ltpb__camera_id__enum_values_by_number[16] =
{
  { "A1", "LTPB__CAMERA_ID__A1", 0 },
  { "A2", "LTPB__CAMERA_ID__A2", 1 },
  { "A3", "LTPB__CAMERA_ID__A3", 2 },
  { "A4", "LTPB__CAMERA_ID__A4", 3 },
  { "A5", "LTPB__CAMERA_ID__A5", 4 },
  { "B1", "LTPB__CAMERA_ID__B1", 5 },
  { "B2", "LTPB__CAMERA_ID__B2", 6 },
  { "B3", "LTPB__CAMERA_ID__B3", 7 },
  { "B4", "LTPB__CAMERA_ID__B4", 8 },
  { "B5", "LTPB__CAMERA_ID__B5", 9 },
  { "C1", "LTPB__CAMERA_ID__C1", 10 },
  { "C2", "LTPB__CAMERA_ID__C2", 11 },
  { "C3", "LTPB__CAMERA_ID__C3", 12 },
  { "C4", "LTPB__CAMERA_ID__C4", 13 },
  { "C5", "LTPB__CAMERA_ID__C5", 14 },
  { "C6", "LTPB__CAMERA_ID__C6", 15 },
};
LIGHT_HEADER_CONST static const ProtobufCIntRange ltpb__camera_id__value_ranges[] = {
{0, 0},{0, 16}
};
LIGHT_HEADER_CONST static const ProtobufCEnumValueIndex ltpb__camera_id__enum_values_by_name[16] =
{
  { "A1", 0 },
  { "A2", 1 },
  { "A3", 2 },
  { "A4", 3 },
  { "A5", 4 },
  { "B1", 5 },
  { "B2", 6 },
  { "B3", 7 },
  { "B4", 8 },
  { "B5", 9 },
  { "C1", 10 },
  { "C2", 11 },
  { "C3", 12 },
  { "C4", 13 },
  { "C5", 14 },
  { "C6", 15 },
};
LIGHT_HEADER_CONST const ProtobufCEnumDescriptor ltpb__camera_id__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ltpb.CameraID",
  "CameraID",
  "Ltpb__CameraID",
  "ltpb",
  16,
  ltpb__camera_id__enum_values_by_number,
  16,
  ltpb__camera_id__enum_values_by_name,
  1,
  ltpb__camera_id__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
