/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: flash_calibration.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif
#include "sections.h"
#include "flash_calibration.pb-c.h"
LIGHT_HEADER_FUNC void   ltpb__flash_calibration__init
                     (Ltpb__FlashCalibration         *message)
{
  LIGHT_HEADER_STATIC static Ltpb__FlashCalibration init_value = LTPB__FLASH_CALIBRATION__INIT;
  *message = init_value;
}
LIGHT_HEADER_FUNC size_t ltpb__flash_calibration__get_packed_size
                     (const Ltpb__FlashCalibration *message)
{
  assert(message->base.descriptor == &ltpb__flash_calibration__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
LIGHT_HEADER_FUNC size_t ltpb__flash_calibration__pack
                     (const Ltpb__FlashCalibration *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ltpb__flash_calibration__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
LIGHT_HEADER_FUNC size_t ltpb__flash_calibration__pack_to_buffer
                     (const Ltpb__FlashCalibration *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ltpb__flash_calibration__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LIGHT_HEADER_FUNC Ltpb__FlashCalibration *
       ltpb__flash_calibration__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ltpb__FlashCalibration *)
     protobuf_c_message_unpack (&ltpb__flash_calibration__descriptor,
                                allocator, len, data);
}
LIGHT_HEADER_FUNC void   ltpb__flash_calibration__free_unpacked
                     (Ltpb__FlashCalibration *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ltpb__flash_calibration__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
LIGHT_HEADER_CONST static const ProtobufCFieldDescriptor ltpb__flash_calibration__field_descriptors[6] =
{
  {
    "ledcool_lux",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Ltpb__FlashCalibration, ledcool_lux),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ledcool_max_lumens",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Ltpb__FlashCalibration, ledcool_max_lumens),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ledcool_cct",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Ltpb__FlashCalibration, ledcool_cct),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ledwarm_lux",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Ltpb__FlashCalibration, ledwarm_lux),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ledwarm_max_lumens",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Ltpb__FlashCalibration, ledwarm_max_lumens),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ledwarm_cct",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Ltpb__FlashCalibration, ledwarm_cct),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
LIGHT_HEADER_CONST static const unsigned ltpb__flash_calibration__field_indices_by_name[] = {
  2,   /* field[2] = ledcool_cct */
  0,   /* field[0] = ledcool_lux */
  1,   /* field[1] = ledcool_max_lumens */
  5,   /* field[5] = ledwarm_cct */
  3,   /* field[3] = ledwarm_lux */
  4,   /* field[4] = ledwarm_max_lumens */
};
LIGHT_HEADER_CONST static const ProtobufCIntRange ltpb__flash_calibration__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
LIGHT_HEADER_CONST const ProtobufCMessageDescriptor ltpb__flash_calibration__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ltpb.FlashCalibration",
  "FlashCalibration",
  "Ltpb__FlashCalibration",
  "ltpb",
  sizeof(Ltpb__FlashCalibration),
  6,
  ltpb__flash_calibration__field_descriptors,
  ltpb__flash_calibration__field_indices_by_name,
  1,  ltpb__flash_calibration__number_ranges,
  (ProtobufCMessageInit) ltpb__flash_calibration__init,
  NULL,NULL,NULL    /* reserved[123] */
};
