/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: hot_pixel_map.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif
#include "sections.h"
#include "hot_pixel_map.pb-c.h"
LIGHT_HEADER_FUNC void   ltpb__hot_pixel_map__hot_pixel_measurement__init
                     (Ltpb__HotPixelMap__HotPixelMeasurement         *message)
{
  LIGHT_HEADER_STATIC static Ltpb__HotPixelMap__HotPixelMeasurement init_value = LTPB__HOT_PIXEL_MAP__HOT_PIXEL_MEASUREMENT__INIT;
  *message = init_value;
}
LIGHT_HEADER_FUNC void   ltpb__hot_pixel_map__init
                     (Ltpb__HotPixelMap         *message)
{
  LIGHT_HEADER_STATIC static Ltpb__HotPixelMap init_value = LTPB__HOT_PIXEL_MAP__INIT;
  *message = init_value;
}
LIGHT_HEADER_FUNC size_t ltpb__hot_pixel_map__get_packed_size
                     (const Ltpb__HotPixelMap *message)
{
  assert(message->base.descriptor == &ltpb__hot_pixel_map__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
LIGHT_HEADER_FUNC size_t ltpb__hot_pixel_map__pack
                     (const Ltpb__HotPixelMap *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ltpb__hot_pixel_map__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
LIGHT_HEADER_FUNC size_t ltpb__hot_pixel_map__pack_to_buffer
                     (const Ltpb__HotPixelMap *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ltpb__hot_pixel_map__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LIGHT_HEADER_FUNC Ltpb__HotPixelMap *
       ltpb__hot_pixel_map__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ltpb__HotPixelMap *)
     protobuf_c_message_unpack (&ltpb__hot_pixel_map__descriptor,
                                allocator, len, data);
}
LIGHT_HEADER_FUNC void   ltpb__hot_pixel_map__free_unpacked
                     (Ltpb__HotPixelMap *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ltpb__hot_pixel_map__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
LIGHT_HEADER_CONST static const ProtobufCFieldDescriptor ltpb__hot_pixel_map__hot_pixel_measurement__field_descriptors[6] =
{
  {
    "data_offset",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Ltpb__HotPixelMap__HotPixelMeasurement, data_offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data_size",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Ltpb__HotPixelMap__HotPixelMeasurement, data_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gain",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Ltpb__HotPixelMap__HotPixelMeasurement, gain),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "exposure",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Ltpb__HotPixelMap__HotPixelMeasurement, has_exposure),
    offsetof(Ltpb__HotPixelMap__HotPixelMeasurement, exposure),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gradient_threshold",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Ltpb__HotPixelMap__HotPixelMeasurement, has_gradient_threshold),
    offsetof(Ltpb__HotPixelMap__HotPixelMeasurement, gradient_threshold),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "black_level_threshold",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Ltpb__HotPixelMap__HotPixelMeasurement, has_black_level_threshold),
    offsetof(Ltpb__HotPixelMap__HotPixelMeasurement, black_level_threshold),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
LIGHT_HEADER_CONST static const unsigned ltpb__hot_pixel_map__hot_pixel_measurement__field_indices_by_name[] = {
  5,   /* field[5] = black_level_threshold */
  0,   /* field[0] = data_offset */
  1,   /* field[1] = data_size */
  3,   /* field[3] = exposure */
  2,   /* field[2] = gain */
  4,   /* field[4] = gradient_threshold */
};
LIGHT_HEADER_CONST static const ProtobufCIntRange ltpb__hot_pixel_map__hot_pixel_measurement__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
LIGHT_HEADER_CONST const ProtobufCMessageDescriptor ltpb__hot_pixel_map__hot_pixel_measurement__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ltpb.HotPixelMap.HotPixelMeasurement",
  "HotPixelMeasurement",
  "Ltpb__HotPixelMap__HotPixelMeasurement",
  "ltpb",
  sizeof(Ltpb__HotPixelMap__HotPixelMeasurement),
  6,
  ltpb__hot_pixel_map__hot_pixel_measurement__field_descriptors,
  ltpb__hot_pixel_map__hot_pixel_measurement__field_indices_by_name,
  1,  ltpb__hot_pixel_map__hot_pixel_measurement__number_ranges,
  (ProtobufCMessageInit) ltpb__hot_pixel_map__hot_pixel_measurement__init,
  NULL,NULL,NULL    /* reserved[123] */
};
LIGHT_HEADER_CONST static const ProtobufCFieldDescriptor ltpb__hot_pixel_map__field_descriptors[1] =
{
  {
    "data",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ltpb__HotPixelMap, n_data),
    offsetof(Ltpb__HotPixelMap, data),
    &ltpb__hot_pixel_map__hot_pixel_measurement__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
LIGHT_HEADER_CONST static const unsigned ltpb__hot_pixel_map__field_indices_by_name[] = {
  0,   /* field[0] = data */
};
LIGHT_HEADER_CONST static const ProtobufCIntRange ltpb__hot_pixel_map__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
LIGHT_HEADER_CONST const ProtobufCMessageDescriptor ltpb__hot_pixel_map__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ltpb.HotPixelMap",
  "HotPixelMap",
  "Ltpb__HotPixelMap",
  "ltpb",
  sizeof(Ltpb__HotPixelMap),
  1,
  ltpb__hot_pixel_map__field_descriptors,
  ltpb__hot_pixel_map__field_indices_by_name,
  1,  ltpb__hot_pixel_map__number_ranges,
  (ProtobufCMessageInit) ltpb__hot_pixel_map__init,
  NULL,NULL,NULL    /* reserved[123] */
};
