/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: lightheader.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif
#include "sections.h"
#include "lightheader.pb-c.h"
LIGHT_HEADER_FUNC void   ltpb__factory_device_calibration__init
                     (Ltpb__FactoryDeviceCalibration         *message)
{
  LIGHT_HEADER_STATIC static Ltpb__FactoryDeviceCalibration init_value = LTPB__FACTORY_DEVICE_CALIBRATION__INIT;
  *message = init_value;
}
LIGHT_HEADER_FUNC size_t ltpb__factory_device_calibration__get_packed_size
                     (const Ltpb__FactoryDeviceCalibration *message)
{
  assert(message->base.descriptor == &ltpb__factory_device_calibration__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
LIGHT_HEADER_FUNC size_t ltpb__factory_device_calibration__pack
                     (const Ltpb__FactoryDeviceCalibration *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ltpb__factory_device_calibration__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
LIGHT_HEADER_FUNC size_t ltpb__factory_device_calibration__pack_to_buffer
                     (const Ltpb__FactoryDeviceCalibration *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ltpb__factory_device_calibration__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LIGHT_HEADER_FUNC Ltpb__FactoryDeviceCalibration *
       ltpb__factory_device_calibration__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ltpb__FactoryDeviceCalibration *)
     protobuf_c_message_unpack (&ltpb__factory_device_calibration__descriptor,
                                allocator, len, data);
}
LIGHT_HEADER_FUNC void   ltpb__factory_device_calibration__free_unpacked
                     (Ltpb__FactoryDeviceCalibration *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ltpb__factory_device_calibration__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
LIGHT_HEADER_FUNC void   ltpb__factory_module_calibration__init
                     (Ltpb__FactoryModuleCalibration         *message)
{
  LIGHT_HEADER_STATIC static Ltpb__FactoryModuleCalibration init_value = LTPB__FACTORY_MODULE_CALIBRATION__INIT;
  *message = init_value;
}
LIGHT_HEADER_FUNC size_t ltpb__factory_module_calibration__get_packed_size
                     (const Ltpb__FactoryModuleCalibration *message)
{
  assert(message->base.descriptor == &ltpb__factory_module_calibration__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
LIGHT_HEADER_FUNC size_t ltpb__factory_module_calibration__pack
                     (const Ltpb__FactoryModuleCalibration *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ltpb__factory_module_calibration__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
LIGHT_HEADER_FUNC size_t ltpb__factory_module_calibration__pack_to_buffer
                     (const Ltpb__FactoryModuleCalibration *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ltpb__factory_module_calibration__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LIGHT_HEADER_FUNC Ltpb__FactoryModuleCalibration *
       ltpb__factory_module_calibration__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ltpb__FactoryModuleCalibration *)
     protobuf_c_message_unpack (&ltpb__factory_module_calibration__descriptor,
                                allocator, len, data);
}
LIGHT_HEADER_FUNC void   ltpb__factory_module_calibration__free_unpacked
                     (Ltpb__FactoryModuleCalibration *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ltpb__factory_module_calibration__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
LIGHT_HEADER_FUNC void   ltpb__color_calibration_gold__init
                     (Ltpb__ColorCalibrationGold         *message)
{
  LIGHT_HEADER_STATIC static Ltpb__ColorCalibrationGold init_value = LTPB__COLOR_CALIBRATION_GOLD__INIT;
  *message = init_value;
}
LIGHT_HEADER_FUNC size_t ltpb__color_calibration_gold__get_packed_size
                     (const Ltpb__ColorCalibrationGold *message)
{
  assert(message->base.descriptor == &ltpb__color_calibration_gold__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
LIGHT_HEADER_FUNC size_t ltpb__color_calibration_gold__pack
                     (const Ltpb__ColorCalibrationGold *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ltpb__color_calibration_gold__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
LIGHT_HEADER_FUNC size_t ltpb__color_calibration_gold__pack_to_buffer
                     (const Ltpb__ColorCalibrationGold *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ltpb__color_calibration_gold__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LIGHT_HEADER_FUNC Ltpb__ColorCalibrationGold *
       ltpb__color_calibration_gold__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ltpb__ColorCalibrationGold *)
     protobuf_c_message_unpack (&ltpb__color_calibration_gold__descriptor,
                                allocator, len, data);
}
LIGHT_HEADER_FUNC void   ltpb__color_calibration_gold__free_unpacked
                     (Ltpb__ColorCalibrationGold *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ltpb__color_calibration_gold__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
LIGHT_HEADER_FUNC void   ltpb__sensor_data__init
                     (Ltpb__SensorData         *message)
{
  LIGHT_HEADER_STATIC static Ltpb__SensorData init_value = LTPB__SENSOR_DATA__INIT;
  *message = init_value;
}
LIGHT_HEADER_FUNC size_t ltpb__sensor_data__get_packed_size
                     (const Ltpb__SensorData *message)
{
  assert(message->base.descriptor == &ltpb__sensor_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
LIGHT_HEADER_FUNC size_t ltpb__sensor_data__pack
                     (const Ltpb__SensorData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ltpb__sensor_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
LIGHT_HEADER_FUNC size_t ltpb__sensor_data__pack_to_buffer
                     (const Ltpb__SensorData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ltpb__sensor_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LIGHT_HEADER_FUNC Ltpb__SensorData *
       ltpb__sensor_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ltpb__SensorData *)
     protobuf_c_message_unpack (&ltpb__sensor_data__descriptor,
                                allocator, len, data);
}
LIGHT_HEADER_FUNC void   ltpb__sensor_data__free_unpacked
                     (Ltpb__SensorData *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ltpb__sensor_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
LIGHT_HEADER_FUNC void   ltpb__light_header__init
                     (Ltpb__LightHeader         *message)
{
  LIGHT_HEADER_STATIC static Ltpb__LightHeader init_value = LTPB__LIGHT_HEADER__INIT;
  *message = init_value;
}
LIGHT_HEADER_FUNC size_t ltpb__light_header__get_packed_size
                     (const Ltpb__LightHeader *message)
{
  assert(message->base.descriptor == &ltpb__light_header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
LIGHT_HEADER_FUNC size_t ltpb__light_header__pack
                     (const Ltpb__LightHeader *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ltpb__light_header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
LIGHT_HEADER_FUNC size_t ltpb__light_header__pack_to_buffer
                     (const Ltpb__LightHeader *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ltpb__light_header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LIGHT_HEADER_FUNC Ltpb__LightHeader *
       ltpb__light_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ltpb__LightHeader *)
     protobuf_c_message_unpack (&ltpb__light_header__descriptor,
                                allocator, len, data);
}
LIGHT_HEADER_FUNC void   ltpb__light_header__free_unpacked
                     (Ltpb__LightHeader *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ltpb__light_header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
LIGHT_HEADER_CONST static const ProtobufCFieldDescriptor ltpb__factory_device_calibration__field_descriptors[3] =
{
  {
    "flash",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ltpb__FactoryDeviceCalibration, flash),
    &ltpb__flash_calibration__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tof",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ltpb__FactoryDeviceCalibration, tof),
    &ltpb__to_fcalibration__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time_stamp",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ltpb__FactoryDeviceCalibration, time_stamp),
    &ltpb__time_stamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
LIGHT_HEADER_CONST static const unsigned ltpb__factory_device_calibration__field_indices_by_name[] = {
  0,   /* field[0] = flash */
  2,   /* field[2] = time_stamp */
  1,   /* field[1] = tof */
};
LIGHT_HEADER_CONST static const ProtobufCIntRange ltpb__factory_device_calibration__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
LIGHT_HEADER_CONST const ProtobufCMessageDescriptor ltpb__factory_device_calibration__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ltpb.FactoryDeviceCalibration",
  "FactoryDeviceCalibration",
  "Ltpb__FactoryDeviceCalibration",
  "ltpb",
  sizeof(Ltpb__FactoryDeviceCalibration),
  3,
  ltpb__factory_device_calibration__field_descriptors,
  ltpb__factory_device_calibration__field_indices_by_name,
  1,  ltpb__factory_device_calibration__number_ranges,
  (ProtobufCMessageInit) ltpb__factory_device_calibration__init,
  NULL,NULL,NULL    /* reserved[123] */
};
LIGHT_HEADER_CONST static const ProtobufCFieldDescriptor ltpb__factory_module_calibration__field_descriptors[7] =
{
  {
    "camera_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Ltpb__FactoryModuleCalibration, camera_id),
    &ltpb__camera_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "color",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ltpb__FactoryModuleCalibration, n_color),
    offsetof(Ltpb__FactoryModuleCalibration, color),
    &ltpb__color_calibration__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "geometry",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ltpb__FactoryModuleCalibration, geometry),
    &ltpb__geometric_calibration__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vignetting",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ltpb__FactoryModuleCalibration, vignetting),
    &ltpb__vignetting_characterization__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hot_pixel_map",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ltpb__FactoryModuleCalibration, hot_pixel_map),
    &ltpb__hot_pixel_map__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dead_pixel_map",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ltpb__FactoryModuleCalibration, dead_pixel_map),
    &ltpb__dead_pixel_map__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time_stamp",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ltpb__FactoryModuleCalibration, time_stamp),
    &ltpb__time_stamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
LIGHT_HEADER_CONST static const unsigned ltpb__factory_module_calibration__field_indices_by_name[] = {
  0,   /* field[0] = camera_id */
  1,   /* field[1] = color */
  5,   /* field[5] = dead_pixel_map */
  2,   /* field[2] = geometry */
  4,   /* field[4] = hot_pixel_map */
  6,   /* field[6] = time_stamp */
  3,   /* field[3] = vignetting */
};
LIGHT_HEADER_CONST static const ProtobufCIntRange ltpb__factory_module_calibration__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
LIGHT_HEADER_CONST const ProtobufCMessageDescriptor ltpb__factory_module_calibration__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ltpb.FactoryModuleCalibration",
  "FactoryModuleCalibration",
  "Ltpb__FactoryModuleCalibration",
  "ltpb",
  sizeof(Ltpb__FactoryModuleCalibration),
  7,
  ltpb__factory_module_calibration__field_descriptors,
  ltpb__factory_module_calibration__field_indices_by_name,
  1,  ltpb__factory_module_calibration__number_ranges,
  (ProtobufCMessageInit) ltpb__factory_module_calibration__init,
  NULL,NULL,NULL    /* reserved[123] */
};
LIGHT_HEADER_CONST static const ProtobufCFieldDescriptor ltpb__color_calibration_gold__field_descriptors[3] =
{
  {
    "camera_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Ltpb__ColorCalibrationGold, camera_id),
    &ltpb__camera_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ltpb__ColorCalibrationGold, n_data),
    offsetof(Ltpb__ColorCalibrationGold, data),
    &ltpb__color_calibration__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time_stamp",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ltpb__ColorCalibrationGold, time_stamp),
    &ltpb__time_stamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
LIGHT_HEADER_CONST static const unsigned ltpb__color_calibration_gold__field_indices_by_name[] = {
  0,   /* field[0] = camera_id */
  1,   /* field[1] = data */
  2,   /* field[2] = time_stamp */
};
LIGHT_HEADER_CONST static const ProtobufCIntRange ltpb__color_calibration_gold__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
LIGHT_HEADER_CONST const ProtobufCMessageDescriptor ltpb__color_calibration_gold__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ltpb.ColorCalibrationGold",
  "ColorCalibrationGold",
  "Ltpb__ColorCalibrationGold",
  "ltpb",
  sizeof(Ltpb__ColorCalibrationGold),
  3,
  ltpb__color_calibration_gold__field_descriptors,
  ltpb__color_calibration_gold__field_indices_by_name,
  1,  ltpb__color_calibration_gold__number_ranges,
  (ProtobufCMessageInit) ltpb__color_calibration_gold__init,
  NULL,NULL,NULL    /* reserved[123] */
};
LIGHT_HEADER_CONST static const ProtobufCFieldDescriptor ltpb__sensor_data__field_descriptors[3] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Ltpb__SensorData, type),
    &ltpb__sensor_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ltpb__SensorData, data),
    &ltpb__sensor_characterization__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time_stamp",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ltpb__SensorData, time_stamp),
    &ltpb__time_stamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
LIGHT_HEADER_CONST static const unsigned ltpb__sensor_data__field_indices_by_name[] = {
  1,   /* field[1] = data */
  2,   /* field[2] = time_stamp */
  0,   /* field[0] = type */
};
LIGHT_HEADER_CONST static const ProtobufCIntRange ltpb__sensor_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
LIGHT_HEADER_CONST const ProtobufCMessageDescriptor ltpb__sensor_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ltpb.SensorData",
  "SensorData",
  "Ltpb__SensorData",
  "ltpb",
  sizeof(Ltpb__SensorData),
  3,
  ltpb__sensor_data__field_descriptors,
  ltpb__sensor_data__field_indices_by_name,
  1,  ltpb__sensor_data__number_ranges,
  (ProtobufCMessageInit) ltpb__sensor_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
LIGHT_HEADER_CONST static const ProtobufCFieldDescriptor ltpb__light_header__field_descriptors[21] =
{
  {
    "image_unique_id_low",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Ltpb__LightHeader, has_image_unique_id_low),
    offsetof(Ltpb__LightHeader, image_unique_id_low),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "image_unique_id_high",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Ltpb__LightHeader, has_image_unique_id_high),
    offsetof(Ltpb__LightHeader, image_unique_id_high),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "image_time_stamp",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ltpb__LightHeader, image_time_stamp),
    &ltpb__time_stamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "image_focal_length",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Ltpb__LightHeader, has_image_focal_length),
    offsetof(Ltpb__LightHeader, image_focal_length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "image_reference_camera",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Ltpb__LightHeader, has_image_reference_camera),
    offsetof(Ltpb__LightHeader, image_reference_camera),
    &ltpb__camera_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_unique_id_low",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Ltpb__LightHeader, has_device_unique_id_low),
    offsetof(Ltpb__LightHeader, device_unique_id_low),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_unique_id_high",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Ltpb__LightHeader, has_device_unique_id_high),
    offsetof(Ltpb__LightHeader, device_unique_id_high),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_model_name",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ltpb__LightHeader, device_model_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_fw_version",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ltpb__LightHeader, device_fw_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_asic_fw_version",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ltpb__LightHeader, device_asic_fw_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_temperature",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ltpb__LightHeader, device_temperature),
    &ltpb__device_temp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "modules",
    12,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ltpb__LightHeader, n_modules),
    offsetof(Ltpb__LightHeader, modules),
    &ltpb__camera_module__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "module_calibration",
    13,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ltpb__LightHeader, n_module_calibration),
    offsetof(Ltpb__LightHeader, module_calibration),
    &ltpb__factory_module_calibration__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_calibration",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ltpb__LightHeader, device_calibration),
    &ltpb__factory_device_calibration__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gold_cc",
    15,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ltpb__LightHeader, n_gold_cc),
    offsetof(Ltpb__LightHeader, gold_cc),
    &ltpb__color_calibration_gold__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sensor_data",
    16,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ltpb__LightHeader, n_sensor_data),
    offsetof(Ltpb__LightHeader, sensor_data),
    &ltpb__sensor_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tof_range",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Ltpb__LightHeader, has_tof_range),
    offsetof(Ltpb__LightHeader, tof_range),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hw_info",
    18,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ltpb__LightHeader, hw_info),
    &ltpb__hw_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "view_preferences",
    19,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ltpb__LightHeader, view_preferences),
    &ltpb__view_preferences__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proximity_sensors",
    20,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ltpb__LightHeader, proximity_sensors),
    &ltpb__proximity_sensors__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "imu_data",
    21,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ltpb__LightHeader, imu_data),
    &ltpb__imudata__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
LIGHT_HEADER_CONST static const unsigned ltpb__light_header__field_indices_by_name[] = {
  9,   /* field[9] = device_asic_fw_version */
  13,   /* field[13] = device_calibration */
  8,   /* field[8] = device_fw_version */
  7,   /* field[7] = device_model_name */
  10,   /* field[10] = device_temperature */
  6,   /* field[6] = device_unique_id_high */
  5,   /* field[5] = device_unique_id_low */
  14,   /* field[14] = gold_cc */
  17,   /* field[17] = hw_info */
  3,   /* field[3] = image_focal_length */
  4,   /* field[4] = image_reference_camera */
  2,   /* field[2] = image_time_stamp */
  1,   /* field[1] = image_unique_id_high */
  0,   /* field[0] = image_unique_id_low */
  20,   /* field[20] = imu_data */
  12,   /* field[12] = module_calibration */
  11,   /* field[11] = modules */
  19,   /* field[19] = proximity_sensors */
  15,   /* field[15] = sensor_data */
  16,   /* field[16] = tof_range */
  18,   /* field[18] = view_preferences */
};
LIGHT_HEADER_CONST static const ProtobufCIntRange ltpb__light_header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 21 }
};
LIGHT_HEADER_CONST const ProtobufCMessageDescriptor ltpb__light_header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ltpb.LightHeader",
  "LightHeader",
  "Ltpb__LightHeader",
  "ltpb",
  sizeof(Ltpb__LightHeader),
  21,
  ltpb__light_header__field_descriptors,
  ltpb__light_header__field_indices_by_name,
  1,  ltpb__light_header__number_ranges,
  (ProtobufCMessageInit) ltpb__light_header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
