/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: range2f.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif
#include "sections.h"
#include "range2f.pb-c.h"
LIGHT_HEADER_FUNC void   ltpb__range2_f__init
                     (Ltpb__Range2F         *message)
{
  static Ltpb__Range2F init_value = LTPB__RANGE2_F__INIT;
  *message = init_value;
}
LIGHT_HEADER_FUNC size_t ltpb__range2_f__get_packed_size
                     (const Ltpb__Range2F *message)
{
  assert(message->base.descriptor == &ltpb__range2_f__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
LIGHT_HEADER_FUNC size_t ltpb__range2_f__pack
                     (const Ltpb__Range2F *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ltpb__range2_f__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
LIGHT_HEADER_FUNC size_t ltpb__range2_f__pack_to_buffer
                     (const Ltpb__Range2F *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ltpb__range2_f__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LIGHT_HEADER_FUNC Ltpb__Range2F *
       ltpb__range2_f__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ltpb__Range2F *)
     protobuf_c_message_unpack (&ltpb__range2_f__descriptor,
                                allocator, len, data);
}
LIGHT_HEADER_FUNC void   ltpb__range2_f__free_unpacked
                     (Ltpb__Range2F *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ltpb__range2_f__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
LIGHT_HEADER_CONST static const ProtobufCFieldDescriptor ltpb__range2_f__field_descriptors[2] =
{
  {
    "min_val",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Ltpb__Range2F, min_val),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_val",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Ltpb__Range2F, max_val),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
LIGHT_HEADER_CONST static const unsigned ltpb__range2_f__field_indices_by_name[] = {
  1,   /* field[1] = max_val */
  0,   /* field[0] = min_val */
};
LIGHT_HEADER_CONST static const ProtobufCIntRange ltpb__range2_f__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
LIGHT_HEADER_CONST const ProtobufCMessageDescriptor ltpb__range2_f__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ltpb.Range2F",
  "Range2F",
  "Ltpb__Range2F",
  "ltpb",
  sizeof(Ltpb__Range2F),
  2,
  ltpb__range2_f__field_descriptors,
  ltpb__range2_f__field_indices_by_name,
  1,  ltpb__range2_f__number_ranges,
  (ProtobufCMessageInit) ltpb__range2_f__init,
  NULL,NULL,NULL    /* reserved[123] */
};
