/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sensor_type.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif
#include "sections.h"
#include "sensor_type.pb-c.h"
LIGHT_HEADER_CONST static const ProtobufCEnumValue ltpb__sensor_type__enum_values_by_number[4] =
{
  { "SENSOR_UNKNOWN", "LTPB__SENSOR_TYPE__SENSOR_UNKNOWN", 0 },
  { "SENSOR_AR835", "LTPB__SENSOR_TYPE__SENSOR_AR835", 1 },
  { "SENSOR_AR1335", "LTPB__SENSOR_TYPE__SENSOR_AR1335", 2 },
  { "SENSOR_AR1335_MONO", "LTPB__SENSOR_TYPE__SENSOR_AR1335_MONO", 3 },
};
LIGHT_HEADER_CONST static const ProtobufCIntRange ltpb__sensor_type__value_ranges[] = {
{0, 0},{0, 4}
};
LIGHT_HEADER_CONST static const ProtobufCEnumValueIndex ltpb__sensor_type__enum_values_by_name[4] =
{
  { "SENSOR_AR1335", 2 },
  { "SENSOR_AR1335_MONO", 3 },
  { "SENSOR_AR835", 1 },
  { "SENSOR_UNKNOWN", 0 },
};
LIGHT_HEADER_CONST const ProtobufCEnumDescriptor ltpb__sensor_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ltpb.SensorType",
  "SensorType",
  "Ltpb__SensorType",
  "ltpb",
  4,
  ltpb__sensor_type__enum_values_by_number,
  4,
  ltpb__sensor_type__enum_values_by_name,
  1,
  ltpb__sensor_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
