/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: tof_calibration.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif
#include "sections.h"
#include "tof_calibration.pb-c.h"
LIGHT_HEADER_FUNC void   ltpb__to_fcalibration__init
                     (Ltpb__ToFCalibration         *message)
{
  LIGHT_HEADER_STATIC static Ltpb__ToFCalibration init_value = LTPB__TO_FCALIBRATION__INIT;
  *message = init_value;
}
LIGHT_HEADER_FUNC size_t ltpb__to_fcalibration__get_packed_size
                     (const Ltpb__ToFCalibration *message)
{
  assert(message->base.descriptor == &ltpb__to_fcalibration__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
LIGHT_HEADER_FUNC size_t ltpb__to_fcalibration__pack
                     (const Ltpb__ToFCalibration *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ltpb__to_fcalibration__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
LIGHT_HEADER_FUNC size_t ltpb__to_fcalibration__pack_to_buffer
                     (const Ltpb__ToFCalibration *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ltpb__to_fcalibration__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LIGHT_HEADER_FUNC Ltpb__ToFCalibration *
       ltpb__to_fcalibration__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ltpb__ToFCalibration *)
     protobuf_c_message_unpack (&ltpb__to_fcalibration__descriptor,
                                allocator, len, data);
}
LIGHT_HEADER_FUNC void   ltpb__to_fcalibration__free_unpacked
                     (Ltpb__ToFCalibration *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ltpb__to_fcalibration__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
LIGHT_HEADER_CONST static const ProtobufCFieldDescriptor ltpb__to_fcalibration__field_descriptors[4] =
{
  {
    "offset_distance",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Ltpb__ToFCalibration, offset_distance),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "offset_measurement",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Ltpb__ToFCalibration, offset_measurement),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "xtalk_distance",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Ltpb__ToFCalibration, xtalk_distance),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "xtalk_measurement",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Ltpb__ToFCalibration, xtalk_measurement),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
LIGHT_HEADER_CONST static const unsigned ltpb__to_fcalibration__field_indices_by_name[] = {
  0,   /* field[0] = offset_distance */
  1,   /* field[1] = offset_measurement */
  2,   /* field[2] = xtalk_distance */
  3,   /* field[3] = xtalk_measurement */
};
LIGHT_HEADER_CONST static const ProtobufCIntRange ltpb__to_fcalibration__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
LIGHT_HEADER_CONST const ProtobufCMessageDescriptor ltpb__to_fcalibration__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ltpb.ToFCalibration",
  "ToFCalibration",
  "Ltpb__ToFCalibration",
  "ltpb",
  sizeof(Ltpb__ToFCalibration),
  4,
  ltpb__to_fcalibration__field_descriptors,
  ltpb__to_fcalibration__field_indices_by_name,
  1,  ltpb__to_fcalibration__number_ranges,
  (ProtobufCMessageInit) ltpb__to_fcalibration__init,
  NULL,NULL,NULL    /* reserved[123] */
};
