/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: vignetting_characterization.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "sections.h"
#include "vignetting_characterization.pb-c.h"
LIGHT_HEADER_FUNC void   ltpb__vignetting_characterization__crosstalk_model__init
                     (Ltpb__VignettingCharacterization__CrosstalkModel         *message)
{
  static Ltpb__VignettingCharacterization__CrosstalkModel init_value = LTPB__VIGNETTING_CHARACTERIZATION__CROSSTALK_MODEL__INIT;
  *message = init_value;
}
LIGHT_HEADER_FUNC void   ltpb__vignetting_characterization__vignetting_model__init
                     (Ltpb__VignettingCharacterization__VignettingModel         *message)
{
  static Ltpb__VignettingCharacterization__VignettingModel init_value = LTPB__VIGNETTING_CHARACTERIZATION__VIGNETTING_MODEL__INIT;
  *message = init_value;
}
LIGHT_HEADER_FUNC void   ltpb__vignetting_characterization__mirror_vignetting_model__init
                     (Ltpb__VignettingCharacterization__MirrorVignettingModel         *message)
{
  static Ltpb__VignettingCharacterization__MirrorVignettingModel init_value = LTPB__VIGNETTING_CHARACTERIZATION__MIRROR_VIGNETTING_MODEL__INIT;
  *message = init_value;
}
LIGHT_HEADER_FUNC void   ltpb__vignetting_characterization__init
                     (Ltpb__VignettingCharacterization         *message)
{
  static Ltpb__VignettingCharacterization init_value = LTPB__VIGNETTING_CHARACTERIZATION__INIT;
  *message = init_value;
}
LIGHT_HEADER_FUNC size_t ltpb__vignetting_characterization__get_packed_size
                     (const Ltpb__VignettingCharacterization *message)
{
  assert(message->base.descriptor == &ltpb__vignetting_characterization__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
LIGHT_HEADER_FUNC size_t ltpb__vignetting_characterization__pack
                     (const Ltpb__VignettingCharacterization *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ltpb__vignetting_characterization__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
LIGHT_HEADER_FUNC size_t ltpb__vignetting_characterization__pack_to_buffer
                     (const Ltpb__VignettingCharacterization *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ltpb__vignetting_characterization__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LIGHT_HEADER_FUNC Ltpb__VignettingCharacterization *
       ltpb__vignetting_characterization__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ltpb__VignettingCharacterization *)
     protobuf_c_message_unpack (&ltpb__vignetting_characterization__descriptor,
                                allocator, len, data);
}
LIGHT_HEADER_FUNC void   ltpb__vignetting_characterization__free_unpacked
                     (Ltpb__VignettingCharacterization *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ltpb__vignetting_characterization__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
LIGHT_HEADER_CONST static const ProtobufCFieldDescriptor ltpb__vignetting_characterization__crosstalk_model__field_descriptors[4] =
{
  {
    "width",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Ltpb__VignettingCharacterization__CrosstalkModel, width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "height",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Ltpb__VignettingCharacterization__CrosstalkModel, height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ltpb__VignettingCharacterization__CrosstalkModel, n_data),
    offsetof(Ltpb__VignettingCharacterization__CrosstalkModel, data),
    &ltpb__matrix4x4_f__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data_packed",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Ltpb__VignettingCharacterization__CrosstalkModel, n_data_packed),
    offsetof(Ltpb__VignettingCharacterization__CrosstalkModel, data_packed),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
LIGHT_HEADER_CONST static const unsigned ltpb__vignetting_characterization__crosstalk_model__field_indices_by_name[] = {
  2,   /* field[2] = data */
  3,   /* field[3] = data_packed */
  1,   /* field[1] = height */
  0,   /* field[0] = width */
};
LIGHT_HEADER_CONST static const ProtobufCIntRange ltpb__vignetting_characterization__crosstalk_model__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
LIGHT_HEADER_CONST const ProtobufCMessageDescriptor ltpb__vignetting_characterization__crosstalk_model__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ltpb.VignettingCharacterization.CrosstalkModel",
  "CrosstalkModel",
  "Ltpb__VignettingCharacterization__CrosstalkModel",
  "ltpb",
  sizeof(Ltpb__VignettingCharacterization__CrosstalkModel),
  4,
  ltpb__vignetting_characterization__crosstalk_model__field_descriptors,
  ltpb__vignetting_characterization__crosstalk_model__field_indices_by_name,
  1,  ltpb__vignetting_characterization__crosstalk_model__number_ranges,
  (ProtobufCMessageInit) ltpb__vignetting_characterization__crosstalk_model__init,
  NULL,NULL,NULL    /* reserved[123] */
};
LIGHT_HEADER_CONST static const ProtobufCFieldDescriptor ltpb__vignetting_characterization__vignetting_model__field_descriptors[3] =
{
  {
    "width",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Ltpb__VignettingCharacterization__VignettingModel, width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "height",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Ltpb__VignettingCharacterization__VignettingModel, height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Ltpb__VignettingCharacterization__VignettingModel, n_data),
    offsetof(Ltpb__VignettingCharacterization__VignettingModel, data),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
LIGHT_HEADER_CONST static const unsigned ltpb__vignetting_characterization__vignetting_model__field_indices_by_name[] = {
  2,   /* field[2] = data */
  1,   /* field[1] = height */
  0,   /* field[0] = width */
};
LIGHT_HEADER_CONST static const ProtobufCIntRange ltpb__vignetting_characterization__vignetting_model__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
LIGHT_HEADER_CONST const ProtobufCMessageDescriptor ltpb__vignetting_characterization__vignetting_model__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ltpb.VignettingCharacterization.VignettingModel",
  "VignettingModel",
  "Ltpb__VignettingCharacterization__VignettingModel",
  "ltpb",
  sizeof(Ltpb__VignettingCharacterization__VignettingModel),
  3,
  ltpb__vignetting_characterization__vignetting_model__field_descriptors,
  ltpb__vignetting_characterization__vignetting_model__field_indices_by_name,
  1,  ltpb__vignetting_characterization__vignetting_model__number_ranges,
  (ProtobufCMessageInit) ltpb__vignetting_characterization__vignetting_model__init,
  NULL,NULL,NULL    /* reserved[123] */
};
LIGHT_HEADER_CONST static const ProtobufCFieldDescriptor ltpb__vignetting_characterization__mirror_vignetting_model__field_descriptors[2] =
{
  {
    "hall_code",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Ltpb__VignettingCharacterization__MirrorVignettingModel, hall_code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vignetting",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ltpb__VignettingCharacterization__MirrorVignettingModel, vignetting),
    &ltpb__vignetting_characterization__vignetting_model__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
LIGHT_HEADER_CONST static const unsigned ltpb__vignetting_characterization__mirror_vignetting_model__field_indices_by_name[] = {
  0,   /* field[0] = hall_code */
  1,   /* field[1] = vignetting */
};
LIGHT_HEADER_CONST static const ProtobufCIntRange ltpb__vignetting_characterization__mirror_vignetting_model__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
LIGHT_HEADER_CONST const ProtobufCMessageDescriptor ltpb__vignetting_characterization__mirror_vignetting_model__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ltpb.VignettingCharacterization.MirrorVignettingModel",
  "MirrorVignettingModel",
  "Ltpb__VignettingCharacterization__MirrorVignettingModel",
  "ltpb",
  sizeof(Ltpb__VignettingCharacterization__MirrorVignettingModel),
  2,
  ltpb__vignetting_characterization__mirror_vignetting_model__field_descriptors,
  ltpb__vignetting_characterization__mirror_vignetting_model__field_indices_by_name,
  1,  ltpb__vignetting_characterization__mirror_vignetting_model__number_ranges,
  (ProtobufCMessageInit) ltpb__vignetting_characterization__mirror_vignetting_model__init,
  NULL,NULL,NULL    /* reserved[123] */
};
LIGHT_HEADER_CONST static const ProtobufCFieldDescriptor ltpb__vignetting_characterization__field_descriptors[2] =
{
  {
    "crosstalk",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ltpb__VignettingCharacterization, crosstalk),
    &ltpb__vignetting_characterization__crosstalk_model__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vignetting",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ltpb__VignettingCharacterization, n_vignetting),
    offsetof(Ltpb__VignettingCharacterization, vignetting),
    &ltpb__vignetting_characterization__mirror_vignetting_model__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
LIGHT_HEADER_CONST static const unsigned ltpb__vignetting_characterization__field_indices_by_name[] = {
  0,   /* field[0] = crosstalk */
  1,   /* field[1] = vignetting */
};
LIGHT_HEADER_CONST static const ProtobufCIntRange ltpb__vignetting_characterization__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
LIGHT_HEADER_CONST const ProtobufCMessageDescriptor ltpb__vignetting_characterization__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ltpb.VignettingCharacterization",
  "VignettingCharacterization",
  "Ltpb__VignettingCharacterization",
  "ltpb",
  sizeof(Ltpb__VignettingCharacterization),
  2,
  ltpb__vignetting_characterization__field_descriptors,
  ltpb__vignetting_characterization__field_indices_by_name,
  1,  ltpb__vignetting_characterization__number_ranges,
  (ProtobufCMessageInit) ltpb__vignetting_characterization__init,
  NULL,NULL,NULL    /* reserved[123] */
};
