#define ELPSMALLCODE
#define ELPSMALLMEM
#define ELPAES
#define ELPAES128
#define ELPAES192
#define ELPAES256
#define ELPCTR
#define ELPSHA256
#define ELPCCM
#define ELPHASHMEM
#define ELPMATH
#define ELPSMALLASN1
#define ELPSPRNG
#define ELPPKCS1
#define ELPRSA
#define ELPECC_NO
#define ELPECC_NO
#define ELPECC_NO
#define ELPECC_NO
#define ELPECC_NO
#define ELPECC_NO
#define ELPECC2_NONO
#define ELPECC2_NO163
#define ELPECC2_NO233
#define ELPECC2_NO283
#define ELPECC2_NO409
#define ELPECC2_NO571
#ifdef ELPASN1
   #undef ELPSMALLASN1
#endif
#define ELPRSANOGEN
#define ELPSMALLMEM
#define ELPSMALLCODE
#define ELPAESENCONLY
